### ISSUE TITLE
Borrar autofirma

### ISSUE THREAD

**Issue by urecio** [ctt-gob-es/clienteafirma#103]
Mi mac ya no confia en ningun certificado y cualquier pagina que abro por https me da error. Como desinstalo esto?

**Comment by Gamuci** [comment]
Para eliminar AutoFirma basta con eliminar la aplicación (.app) del listado de aplicaciones.

También deberías eliminar los dos certificados que se agregan al llavero del sistema. Los reconocerás porque en ellos pone "AutoFirma".

Por si acaso, y para eliminar todo rastro, puedes ver si existe en tu directorio de usuario el subdirectorio "Library/Application Support/AutoFirma". Si es así, elimínalo también.
