### ISSUE TITLE
Problema en el paquete afirma-crypto-core-xml 1.6.5

### ISSUE THREAD

**Issue by DJMolina** [ctt-gob-es/clienteafirma#105]
Buenas tardes,

Hemos detectado un problema a la hora de realizar firmas XAdES trifásicas.
el método es.gob.afirma.signers.xml.Utils.getDOMFactory() prioriza la libreria xmlsec(apache) por encima de la implementacion por defecto de java, cosa que no está mal, sin embargo, el problema viene más adelante.
La clase es.gob.afirma.signers.xades.AOXMLAdvancedSignature extiende de es.uji.crypto.xades.jxades.security.xml.XAdES.XMLAdvancedSignature y dentro de la misma el  método getXMLSignatureFactory instancia la factoria por defecto de java.
Esto desemboca en un ClassCastException, no puede castera de org.apache....DOMReference a org...DOMReference

En nuestro caso, incluimos la libreria de apache en el tomcat, por lo que nos extrañaba que la llegase a encontrar, asique hemos revisado el comportamiento en la anterior release.

El método también prioriza la libreria de apache, pero en ejecución no es capaz de instanciarla, por lo que utiliza la implementación por defecto de java y la operación se resuelve sin problemas.

Si revisamos el pom de afirma-crypto-core-xml 1.6.5 disponible en GitHub vemos que existe lo siguiente:
```
<dependency>
	<groupId>org.apache.santuario</groupId>
        <artifactId>xmlsec</artifactId>
        <version>2.1.3</version>
</dependency>
```

Esta dependencia no está en la versión anterior (1.6.3) y tampoco en el compilado afirma-server-triphase-signer_v2.9 (6677  KB · ZIP) disponible en el PAe

Eliminado la dependencia del pom, todo funciona con normalidad
¿De verdad es necesaria su inclusión para la versión 1.6.5?
¿Qué soluciona?

Un saludo.

**Comment by Gamuci** [comment]
Es un cambio que se hizo hace tiempo, así que respondo de memoria.

A partir de Java 11, se empieza a utilizar internamente la clase pública de Base 64 incorporada en Java 8 (`java.util.Base64`) para procesar los XML , en lugar de una clase interna Base64 que había antes. Esto hacía que las firmas XAdES generadas con esas versiones de Java mostrase en los Base 64 internos del XML (como el Base 64 de los datos firmados) un salto de línea codificado al final de cada línea del Base 64 (`&#13;`).

Para remediar esto, se utilizó una opción de configuración que incorporaba Apache Santuario para omitir los saltos de línea de los XML (`org.apache.xml.security.ignoreLineBreaks`), pero esto era una característica de una versión de Apache Santuario superior a la que incorporaba Java, por eso hubo que agregar externamente la nueva versión (aunque las últimas versiones de Java ya sí está).

Es cierto que esto provoca errores en el servicio de firma trifásica, por lo que se ha modificado el pom de uno de los módulo de este servicio (afirma-server-triphase-signer-core) para excluir la dependencia de Apache Santuario que se importaba a través de afirma-crypto-core-xml.

		<dependency>
			<groupId>es.gob.afirma</groupId>
			<artifactId>afirma-crypto-xades</artifactId>
			<version>${clienteafirma.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.santuario</groupId>
		    			<artifactId>xmlsec</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

Dejo un par de enlaces:

[https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8177334](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8177334)
[https://issues.apache.org/jira/browse/SANTUARIO-482](https://issues.apache.org/jira/browse/SANTUARIO-482)

Gracias.
