### ISSUE TITLE
Duda sobre la validación de las firmas.

### ISSUE THREAD

**Issue by AndresCaballeroMancera** [ctt-gob-es/clienteafirma#106]
Buenos dias,
En primer lugar, mencionar que estoy utilizando el proyecto "afirma-ui-miniapplet-deploy" ya que, gracias a él, puedo firmar formularios HTML según sus campos.
He realizado la firma de dichos campos y su guardado en un fichero, pero no consigo validar esa firma, o al menos ver, quienes la han firmado. 
Autofirma tiene la opción de "ver firmas", pero no se como implementar esto en este ejemplo.
Un saludo.

**Comment by Gamuci** [comment]
AutoFirma permite realizar una verificación de la criptográfica de las firmas y la caducidad de los certificados, pero no realiza un proceso de validación completo. Estas funcionalidades, además, sólo están disponibles a través de la interfaz de escritorio.

Si únicamente desea validar una firma, puede utilizar un servicio de validación como [VALIDe](https://valide.redsara.es/valide/).

Si desea validar firmas como parte de algún proceso, deberá conectar con algún sistema de validación de validación de firmas.
