### ISSUE TITLE
Como poner la firma visible en un pdf en firma-ui-miniapplet-deploy

### ISSUE THREAD

**Issue by ocutino86** [ctt-gob-es/clienteafirma#107]
Estoy usando el modulo de firma-ui-miniapplet-deploy con autoFirma y me funciona correctamente pero no me pone la firma visible en el PDF, saben como resolver este problema.
Gracias.

**Comment by jon2218** [comment]
Hola ocutino86, estoy integrando el modulo de firma-ui-miniapplet-deploy y me da el siguiente error, No se ha podido obtener el flujo de salida del fichero en la consola de java, sabes porque es?

**Comment by Gamuci** [comment]
Él módulo "afirma-ui-miniapplet-deploy" es el que aloja el JavaScript de despliegue del Cliente @firma y las páginas de prueba. No está pensado para empaquetarlo.

Los parámetros para la configuración de la firma visible PDF está en el manual del integrador del Cliente @firma. Se puede acceder a la última versión de este manual desde [este enlace](https://github.com/ctt-gob-es/clienteafirma-docs/blob/master/MCF_manual-integrador_ES.docx). La versión actual del manual está orientado al uso de AutoFirma 1.7, aunque eso no afecta a las opciones de visualización de firmas (salvo el rotado).
