### ISSUE TITLE
¿Fichero Changelog.md?

### ISSUE THREAD

**Issue by szarza** [ctt-gob-es/clienteafirma#108]
Hola:
Hay alguna forma de saber qué incluyen las versiones? Me gustaría saber qué nuevas características, modificaciones y bugfixes incluyen las versiones superiores a la 1.6.2.

He buscado ficheros de historial de cambios changelog.md, release.md o history.md o similar y no los encuentro

Gracias.

**Comment by albfernandez** [comment]
Están en otro proyecto, clienteafirm-docs

El que buscas es este
https://github.com/ctt-gob-es/clienteafirma-docs/blob/master/AF_whatsnew_ES.txt

**Comment by szarza** [comment]
Perfecto. Muchas gracias!
