### ISSUE TITLE
Dificultades con el funcionamiento en navegador

### ISSUE THREAD

**Issue by Dennywuh** [ctt-gob-es/clienteafirma#109]
He instalado AutoFirma y ha funcionado en la firma de documentos pero no en el navegador. El resultado es «No se han encontrado certificados válidos en el almacén.»

Cumplo los requisitos previos, tengo certificados válidos y necesito que funcione porque un trámite me lo exige, así que busco solución.

La primera sorpresa es que AutoFirma no tiene servicio de atención al usuario. Al contrario, se han cuidado mucho de no publicar un contacto susceptible de ser usado para este fin. La siguiente sorpresa es el gran número de ministerios, diputaciones y gobiernos autonómicos que tienen una web, un PDF, un correo electrónico y un teléfono para ayudar al usuario con AutoFirma. Lógicamente, esta consecuencia es producto de la anterior. El tercer asombro es la cantidad de problemas que produce, más aún teniendo en cuenta que su cometido es facilitar la relación del ciudadano con la administración.

De las muchas fuentes encontradas he probado esto:
  - Desinstalar AutoFirma y volver a instalar.
  - Borrar las cachés de Firefox.
  - Iniciar Firefox con los complementos desactivados.
  - Desinstalar el antivirus antes de instalar AutoFirma.
  - Borrar el certificado raíz de AutoFirma y volver a importarlo.
  - Borrar los archivos temporales de Java.
  - Desinstalar Java 32bit y dejar sólo 64bit, y desinstalar Java 64bit y dejar sólo 32bit.
  - Instalar Java 11.
  - Desinstalar AutoFirma 64bit (aunque sea la que corresponde) e instalar 32bit.

Ninguna de estas acciones solucionó el problema, y algunas lo empeoraron. Al final un _issue_ en este repositorio (#86, muchísimas gracias **@rmunozrodriguez**) aportó el remedio:
  - Eliminar perfiles secundarios de Firefox.

Todo esto viene a plantear la siguiente pregunta: ¿No es hora de que AutoFirma tenga servicio de atención al usuario? No tenerlo es arrogante, porque asume que el software es perfecto. Como hemos visto, este no es el caso. No tenerlo es mezquino, pues fuerza a las administraciones que lo implementan a dedicar tiempo y recursos a ayudar al ciudadano, lo que no es su obligación y para lo cual no están preparadas. No tenerlo es contraproducente, ya que es un producto destinado a mejorar la relación del usuario con la administración, y cuando no funciona consigue el resultado opuesto: desesperar, indignar y enojar al ciudadano.

Saludos,

D

**Comment by Gamuci** [comment]
Buenas tardes,

Se ha corregido el problema de selección del perfil de Firefox. Esta corrección estará disponible en AutoFirma 1.7.

El Cliente @firma es un producto del Ministerio de asuntos económicos y transformación digital, pensado para uso por parte de aplicaciones de tramitación internas y la realización de gestiones por parte de los ciudadanos, y puesto a disposición general como software libre.

Si surgen problemas con AutoFirma en la realización de cualquier trámite con la administración, pueden notificarse los errores a través de dicha administración. En cualquier caso, los ciudadanos pueden comunicar cualquier incidencia a través del [punto de acceso general](https://administracion.gob.es/pag_Home/index.html) para la comunicación con las administraciones públicas. Cualquier incidencia es redirigida a través de este canal a los responsables correspondientes. Los avisos pueden realizarse, por ejemplo, a través del teléfono [060](tel:060) o su [WebChat](https://administracion.gob.es/pag_Home/contacto/WebChat0.html#.Xo22Js77RPY).
