### ISSUE TITLE
Autofirma: No accede al almacen de firma en las ultimas versiones de Firefox

### ISSUE THREAD

**Issue by abelardoacosta** [ctt-gob-es/clienteafirma#114]
Con las últimas versiones de Firefox, cuando llama a Autofirma no funciona correctamente porque no puede leer/acceder a las firmas digitales. Sale vacío y no se puede seleccionar certificado digital instalado. Este problema me da en Windows 10 en Firefox 69 o superior

**Comment by juanfcocontreras** [comment]
El mi problema, pero en mi caso probado con Firefox 68 ESR y Firefox 70 en un Mac OSX 10.15.

**Comment by albfernandez** [comment]
Creo recordar que habia un problema con esas verisones que creaba dos profiles y autofirma leía el "malo"
Como workaround podeis probar a eliminar uno de ellos :
Ir a la dirección about:profiles, y si os salen dos profiles borrar el que no es, que no estoy muy seguro de como se sabe.

**Comment by juanfcocontreras** [comment]
Efectivamente, había dos perfiles en mi caso. He eliminado el que no uso y ya salen los certificados disponibles.

¡Muchas gracias!

**Comment by carlossc87** [comment]
Duplicate of #86

**Comment by Gamuci** [comment]
Había varios problemas en el algoritmo para la selección del perfil de Firefox. Se ha mejorado el proceso para que se seleccione el último perfil activo (que debería ser el del Firefox actualmente abierto). Con esto quedaría resuelto el problema.
