### ISSUE TITLE
Autofirma_1_6_5 en Ubunto 20.04 - "El almacén no contiene ningún certificado(...)"

### ISSUE THREAD

**Issue by Antogneco** [ctt-gob-es/clienteafirma#127]
Hola,

En primer lugar quiero pedir disculpas si esta consulta ya ha sido respondida y no lo he encontrado por ninguna parte. Creo que es importante decir antes de empezar que no tengo idea alguna sobre programación.

Permitan que les explique: Tras la actualización al Ubuntu 20.04 no he logrado hacer que el Autofirma conecte con mis certificados. Seguí los pasos de este modo:

1. Instalar OpenJDK 8
2. Instalar Libnss3-tools
3. Instalar los Certificados en Firefox
4. Descargar Chrome e instalar los Certificados
5. Instalar Autofirma 1.6.5

Pese a que el programa corre sin ningún problema aparente, me muestra mi almacén de certificados vacío y luego me dice que "El almacén no contiene ningún certificado que se pueda usar para firmar".

La verdad que no sé qué hacer. Les adjunto el log del Autofirma para ver si pueden echarme una mano. ¡Muchas gracias!

[AUTOFIRMA.afirma.log.txt](https://github.com/ctt-gob-es/clienteafirma/files/4535273/AUTOFIRMA.afirma.log.txt)

**Comment by alfem** [comment]
Sabes cuantos perfiles de firefox tienes?

**Comment by jaragunde** [comment]
Tengo el mismo problema con Autofirma 1.6.5 y Firefox 76.0.1 en Fedora 31. Tengo dos perfiles de Firefox (lanzar `firefox -P`), si elimino uno de ellos las firmas del perfil restante aparecen.

**Comment by Gamuci** [comment]
Después de la publicación de AutoFirma 1.6.5 se han realizado mejoras en cuanto a la detección del perfil activo de Firefox. He probado en Ubuntu 20.04 y la aplicación detecta cual es el último perfil de Firefox utilizado y accede a los certificados de ese perfil. Los cambios estarán disponibles en la próxima versión de AutoFirma.
