### ISSUE TITLE
Fallo inesperado en el componente de firma: SAF_33: La contraseña proporcionada no es válida para el PDF actual o no se proporciona ninguna contraseᡮ.

### ISSUE THREAD

**Issue by lolomovil** [ctt-gob-es/clienteafirma#134]
Al realizar la firma de un documento mediante portafirma recibo este error. No he encontrado que significa ni modo de solucionarlo.

**Comment by Gamuci** [comment]
Ya había otro issue comentando este tema, pero no se puede probar nada si ni siquiera tenemos el PDF. Envía la incidencia al CAU de la herramienta Portafirmas a través del canal habitual. Ellos ya nos harán llegar la incidencia si consideran que es problema del Cliente @firma.

Gracias.

**Comment by lolomovil** [comment]
Muchas gracias, al final el problema lo provocaba el pdf a firmar. Estaba ya firmado y solo dejaba dar visto bueno,

**Comment by ferdymercury** [comment]
He visto un problema similar con un PDF que estaba encriptado, pero sin contraseña. Esto lo solucionó:

`qpdf --decrypt Vacaciones_centros.pdf Vacaciones_centros_decrypted.pdf`
