### ISSUE TITLE
Publicar checksums de los instalables para descarga, firmados con GPG.

### ISSUE THREAD

**Issue by tinproject** [ctt-gob-es/clienteafirma#136]
No soy capaz de encontrar shasums y firmas de los descargables de Autofirma (AutoFirma_Linux.zip) para comprobar su origen.

Deberíais publicar shasums de los instaladores/paquetes para poder verificar su integridad, y firmados por una clave GPG reconocida para poder verificar también su origen, de acuerdo con las buenas prácticas aceptadas de distribución de software.

**Comment by Gamuci** [comment]
Gracias Agustín. Hace poco nos dijeron también firmar los instaladores de Linux con claves PGP. Espero que se generen próximamente y poder subir versiones firmadas. Se valorará también lo de publicar los hashes de los ficheros descargables.

**Comment by Gamuci** [comment]
Me han confirmado que las siguientes versiones de AutoFirma se publicarán junto a sus hashes y que el instalador Linux estará firmado con una clave GPG. No se hará con la versión actualmente publicada.
