### ISSUE TITLE
Rotado de la firma PDF

### ISSUE THREAD

**Issue by CGBMiguel** [ctt-gob-es/clienteafirma#138]
Buenos días, lo primero muchas gracias por el aporte de esta gran aplicación, es de gran ayuda y muy fácil de usar.
Tengo un pequeño problema con el rotado de la firma en  [PDF.](https://github.com/ctt-gob-es/clienteafirma/pull/93/commits/4ee7829fdff519ea499fdde6624834687c18b625)

Veo que la tenéis incorporada al desarrollo, pero la versión de Autofirma 1.6.5 está generada antes de ese cambio.

Mi primera pregunta es si tenéis pensado sacar pronto una nueva versión de Autofirma para incluir esta funcionalidad.

La segunda pregunta la hago desde el desconocimiento. Según veo en el cambio, lo que hace es rotar la capa donde luego establece la firma, entiendo que por ese motivo no se puede incluir la imagen ya que sería complicado ajustarla. En Adobe tienes 
una opción de rotas a la derecha el lienzo (o algo así) sin modificar ni girar el documento ni sus propiedades y posibles firmas. De tal manera que al estampar la firma la hace de manera normal (como el lienzo está rotado realmente la firma la estampa rotada).
Os pongo unas imágenes para que veáis como se puede hacer y mi pregunta es si esta funcionalidad se puede hacer y si tenéis pensado incluir algo parecido.

![image](https://user-images.githubusercontent.com/66054795/87157916-3b709f00-c2bf-11ea-93d7-e6ce4a195286.png) 
![image](https://user-images.githubusercontent.com/66054795/87158427-0153cd00-c2c0-11ea-9e8c-f6b86a174960.png)

**Comment by Gamuci** [comment]
Hola @CGBMiguel,

AutoFirma 1.7 estaba planificado para principios de año, pero este año tan interesante ha hecho que se retrase todo. Ahora mismo la versión está funcionalmente cerrada y a la espera de terminar las pruebas en los diversos sistemas (lo que puede llevar tiempo en estas fechas). A más tardar, esperamos que se publique en septiembre.

AutoFirma inserta las firmas en los PDF a través de iText 2.1.7, la última versión de iText con licencia compatible, que no da demasiadas opciones para configurar la firma.

El poder agregar la imagen rotada a la firma es una funcionalidad que nos gustaría agregar y a ver cuándo se puede hacer. Por ahora, el efecto es el que muestro en las siguientes imágenes.

![1](https://user-images.githubusercontent.com/5908736/87675876-39538800-c778-11ea-8573-ac2f8b5b37e1.png)
![2](https://user-images.githubusercontent.com/5908736/87675901-3eb0d280-c778-11ea-9d8f-52511dda1118.png)
![3](https://user-images.githubusercontent.com/5908736/87675915-41abc300-c778-11ea-820c-5d8599cc83ab.png)
![4](https://user-images.githubusercontent.com/5908736/87675924-453f4a00-c778-11ea-8878-584f44dbe267.png)

Un saludo.

**Comment by CGBMiguel** [comment]
Muchas gracias por la información @Gamuci esperaremos a la próxima versión 1.7. También esperamos la modificación de la imagen cuando sea posible.

Un saludo.
