### ISSUE TITLE
Error al compilar con OpenJDK v1.8: no hay javaws disponible

### ISSUE THREAD

**Issue by olea** [ctt-gob-es/clienteafirma#15]
Hola:

He actualizado el código a la v1.6.

Compilo con:  mvn install -Denv=install  -Dgpg.skip -Dmaven.test.skip=true

Mi entorno de compilación es OpenJDK v1.8, concretamente java-1.8.0-openjdk-1.8.0.141-1.b16.fc24.x86_64

```
$ javac -version
javac 1.8.0_141

```

Pero al lanzar la compilación se queda interrumpida quejándose de la, obvia, carencia de javaws, que no está disponible en v1.8:

```

[ERROR] Failed to execute goal on project afirma-ui-simpleafirma-webstart: Could not resolve dependencies for project es.gob.afirma:afirma-ui-simpleafirma-webstart:jar:1.6: Could not find artifact javax.jnlp:jnlp-api:jar:8.0 at specified path /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.fc24.x86_64/jre/lib/javaws.jar -> [Help 1]
```
FYI

**Comment by Gamuci** [comment]
Hola Ismael,

Lo reviso para que al menos compile. En cualquier caso, ese proyecto es el
de la aplicación WebStart, que nunca se va a poder ejecutar si no se tiene
javaws. El proyecto afirma-simple, que es el de AutoFirma, no os da
problemas, ¿verdad?

Un saludo,

     Carlos Gamuci

**Comment by olea** [comment]
> Lo reviso para que al menos compile. En cualquier caso, ese proyecto es el
de la aplicación WebStart, que nunca se va a poder ejecutar si no se tiene
javaws. El proyecto afirma-simple, que es el de AutoFirma, no os da
problemas, ¿verdad?

Vale, voy entendiendo mucho mejor. Y sí, te confirmo que aparentemente ya sí puedo compilar  afirma-simple  en OpenJDK v8.  Tendré que verificarlo de nuevo con una configuración limpia y después con v9.

Por tanto debo cerrar este parte.
