### ISSUE TITLE
No se encuentra certificados en Ubuntu 20.10 - Error SAF_19

### ISSUE THREAD

**Issue by dtalens** [ctt-gob-es/clienteafirma#162]
Hola, 

Tras actualizar a Ubuntu 20.10 desde Ubuntu 20.04, Autofirma ha dejado de "ver" los certificados instalados, tanto desde los exploradores (chrome y firefox) como dede la propia app. 

He probado a desinstalar certificados, autofirma, borrar sesiones en Chrome y firefox, he probado diversas versiones de java. No he conseguido solucionarlo. Parece un error con las librerías NSS... puede ser?

`openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-8u272-b10-0ubuntu1~20.10-b10)
OpenJDK 64-Bit Server VM (build 25.272-b10, mixed mode)
`

`de nov. 03, 2020 11:31:06 AM es.gob.afirma.standalone.ProxyUtil clearJavaProxy
INFO: No se usara Proxy para las conexiones de red
de nov. 03, 2020 11:31:06 AM es.gob.afirma.standalone.SimpleAfirma main
INFO: No se buscaran nuevas versiones de la aplicacion
de nov. 03, 2020 11:31:06 AM es.gob.afirma.standalone.SimpleAfirma printSystemInfo
INFO: AutoFirma 1.6.5
Resolucion DPI de pantalla: 0
Sistema operativo: Linux
Version del SO: 5.8.0-26-generic
Version de Java: 1.8.0_272
Arquitectura del JRE: 64
Java Vendor: Private Build
Localizacion por defecto: ca_ES
Tamano actual en memoria: 150MB
Tamano maximo de memoria: 1749MB
Memoria actualmente libre: 82MB
de nov. 03, 2020 11:31:06 AM es.gob.afirma.standalone.SimpleAfirma main
INFO: Apertura como herramienta de escritorio
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
de nov. 03, 2020 11:31:06 AM es.gob.afirma.standalone.SimpleAfirma main
INFO: Se intenta una precarga temprana de NSS
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNSS
INFO: Configuracion de NSS para SunPKCS11:
name=NSSCrypto-AFirma
library=/usr/lib/i386-linux-gnu/nss/libsoftokn3.so
attributes=compatibility
slot=2
showInfo=false
allowSingleThreadedModules=true
nssArgs="configdir='sql:/USERHOME/.mozilla/firefox/4edojwky.default' certPrefix='' keyPrefix='' flags='readOnly'"
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNssJava8
INFO: NSS necesita una precarga o tratamiento de sus dependencias: java.lang.reflect.InvocationTargetException
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNssJava8
WARNING: Ha fallado el segundo intento de carga de NSS: java.lang.reflect.InvocationTargetException
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.mozilla.NssKeyStoreManager getNssProvider
SEVERE: Error obteniendo el proveedor NSS: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNssJava8(MozillaKeyStoreUtilities.java:680)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNSS(MozillaKeyStoreUtilities.java:727)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.getNssProvider(NssKeyStoreManager.java:122)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.init(NssKeyStoreManager.java:59)
	at es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager.init(MozillaUnifiedKeyStoreManager.java:72)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getNssKeyStoreManager(AOKeyStoreManagerFactory.java:511)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getMozillaUnifiedKeyStoreManager(AOKeyStoreManagerFactory.java:542)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getAOKeyStoreManager(AOKeyStoreManagerFactory.java:133)
	at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:646)
Caused by: java.security.ProviderException: Initialization failed
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:387)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:107)
	... 13 more
Caused by: java.io.IOException: /usr/lib/i386-linux-gnu/nss/libsoftokn3.so: la classe ELF no és vàlida: ELFCLASS32/usr/lib/i386-linux-gnu/nss/libsoftokn3.so
	at sun.security.pkcs11.wrapper.PKCS11.connect(Native Method)
	at sun.security.pkcs11.wrapper.PKCS11.<init>(PKCS11.java:144)
	at sun.security.pkcs11.wrapper.PKCS11.getInstance(PKCS11.java:157)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:324)
	... 14 more

de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.AOKeyStoreManager init
INFO: Inicializamos el almacen de tipo: DNIe y tarjetas FNMT-TIF
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.KeyStoreUtilities addPreferredKeyStoreManagers
INFO: No se ha encontrado un DNIe: java.security.ProviderException: No se ha podido inicializar el proveedor de DNIe: es.gob.jmulticard.apdu.connection.NoReadersFoundException: No se han podido listar los lectores del sistema: javax.smartcardio.CardException: list() failed: javax.smartcardio.CardException: list() failed
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.AOKeyStoreManager init
INFO: Inicializamos el almacen de tipo: Tarjeta FNMT-RCM CERES 4.30 o superior
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.KeyStoreUtilities addPreferredKeyStoreManagers
INFO: No se ha encontrado una tarjeta CERES 4.30 o superior: java.security.ProviderException: No se ha podido inicializar el proveedor de Ceres 4.30 y superior: es.gob.jmulticard.apdu.connection.NoReadersFoundException: No se han podido listar los lectores del sistema: javax.smartcardio.CardException: list() failed: javax.smartcardio.CardException: list() failed
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.AOKeyStoreManager init
INFO: Inicializamos el almacen de tipo: Tarjeta FNMT-RCM CERES
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.KeyStoreUtilities addPreferredKeyStoreManagers
INFO: No se ha encontrado una tarjeta CERES: java.security.ProviderException: No se ha podido conectar con la tarjeta CERES: es.gob.jmulticard.apdu.connection.NoReadersFoundException: No se han podido listar los lectores del sistema: javax.smartcardio.CardException: list() failed: javax.smartcardio.CardException: list() failed
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities getMozillaPKCS11Modules
INFO: Se incluiran los modulos nativos de DNIe/CERES si se encuentran configurados
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities getMozillaPKCS11Modules
INFO: Obtenidos los modulos externos de Mozilla desde 'pkcs11.txt'
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager init
INFO: Encontrados los siguientes modulos PKCS#11 externos instalados en Mozilla / Firefox: '/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so' 
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.AOKeyStoreManager init
INFO: Inicializamos el almacen de tipo: PKCS#11
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.KeyStoreUtilities createPKCS11ConfigFile
INFO: Creada configuracion PKCS#11:
library=/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so
name=opensc-pkcs11_so
showInfo=true

Information for provider SunPKCS11-opensc-pkcs11_so
Library info:
  cryptokiVersion: 2.20
  manufacturerID: OpenSC Project                  
  flags: 0
  libraryDescription: OpenSC smartcard framework      
  libraryVersion: 0.20
All slots: (none)
Slots with tokens: (none)
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.AOKeyStoreManagerHelperPkcs11 initPKCS11
WARNING: Ha fallado el primer intento de inicializacion del PKCS#11 para la la biblioteca '/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so', se reintentara: java.lang.reflect.InvocationTargetException
Information for provider SunPKCS11-opensc-pkcs11_so
Library info:
  cryptokiVersion: 2.20
  manufacturerID: OpenSC Project                  
  flags: 0
  libraryDescription: OpenSC smartcard framework      
  libraryVersion: 0.20
All slots: (none)
Slots with tokens: (none)
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.AOKeyStoreManager init
INFO: Inicializamos el almacen de tipo: PKCS#11
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.KeyStoreUtilities createPKCS11ConfigFile
INFO: Creada configuracion PKCS#11:
library=/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so
name=opensc-pkcs11_so
showInfo=true

Information for provider SunPKCS11-opensc-pkcs11_so
Library info:
  cryptokiVersion: 2.20
  manufacturerID: OpenSC Project                  
  flags: 0
  libraryDescription: OpenSC smartcard framework      
  libraryVersion: 0.20
All slots: (none)
Slots with tokens: (none)
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.AOKeyStoreManagerHelperPkcs11 initPKCS11
WARNING: Ha fallado el primer intento de inicializacion del PKCS#11 para la la biblioteca '/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so', se reintentara: java.lang.reflect.InvocationTargetException
Information for provider SunPKCS11-opensc-pkcs11_so
Library info:
  cryptokiVersion: 2.20
  manufacturerID: OpenSC Project                  
  flags: 0
  libraryDescription: OpenSC smartcard framework      
  libraryVersion: 0.20
All slots: (none)
Slots with tokens: (none)
de nov. 03, 2020 11:31:06 AM es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager init
WARNING: No se ha podido inicializar el PKCS#11 'DNIe' tras haberlo intentado dos veces: es.gob.afirma.keystores.AOKeyStoreManagerException: No se ha podido instanciar el proveedor SunPKCS11 para la la biblioteca '/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so': java.lang.reflect.InvocationTargetException, es.gob.afirma.keystores.AOKeyStoreManagerException: No se ha podido instanciar el proveedor SunPKCS11 para la la biblioteca '/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so': java.lang.reflect.InvocationTargetException
de nov. 03, 2020 11:31:06 AM es.gob.afirma.standalone.SimpleAfirma setKeyStoreManager
INFO: Establecido KeyStoreManager: Gestor de almacenes de claves Mozilla / Firefox (unificado) con nombre Mozilla / Firefox (unificado)
de nov. 03, 2020 11:31:06 AM es.gob.afirma.standalone.SimpleAfirma main
INFO: Cargando plugins
de nov. 03, 2020 11:31:06 AM es.gob.afirma.standalone.SimpleAfirma main
INFO: Iniciando entorno grafico
de nov. 03, 2020 11:31:06 AM es.gob.afirma.standalone.SimpleAfirma initialize
INFO: No se ha podido obtener la lista de lectores de tarjetas del sistema: javax.smartcardio.CardException: list() failed
de nov. 03, 2020 11:31:06 AM es.gob.afirma.standalone.ui.SignPanel$UpperPanel createUI
WARNING: No ha sido posible obtener la lista de lectores de tarjetas del sistema: javax.smartcardio.CardException: list() failed
de nov. 03, 2020 11:31:06 AM es.gob.afirma.standalone.SimpleAfirma loadDefaultKeyStore
INFO: Se omite la carga concurrente de almacen por haberse hecho una precarga previa
de nov. 03, 2020 11:31:13 AM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for a73 (31) in font ITIIKQ+ZapfDingbatsITC
de nov. 03, 2020 11:31:14 AM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for a73 (31) in font ITIIKQ+ZapfDingbatsITC
de nov. 03, 2020 11:31:15 AM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for a73 (31) in font ITIIKQ+ZapfDingbatsITC
de nov. 03, 2020 11:31:20 AM es.gob.afirma.standalone.ui.pdf.SignPdfDialog positionSelected
INFO: Propiedades establecidas mediante GUI: {layer2Text=Signat per $$SUBJECTCN$$ el dia $$SIGNDATE=dd/MM/yyyy$$ amb un certificat emès per $$ISSUERCN$$, layer2FontFamily=0, signaturePositionOnPageUpperRightY=159, signaturePositionOnPageUpperRightX=430, layer2FontSize=8, layer2FontStyle=0, signaturePositionOnPageLowerLeftY=86, signaturePositionOnPageLowerLeftX=161, signaturePage=1, layer2FontColor=black}
de nov. 03, 2020 11:31:20 AM es.gob.afirma.keystores.AggregatedKeyStoreManager getAliases
WARNING: No se pudieron obtener los alias del almacen Mozilla / Firefox (unificado): java.lang.IllegalStateException: Se han pedido alias a un almacen no inicializado
de nov. 03, 2020 11:31:20 AM es.gob.afirma.keystores.AggregatedKeyStoreManager getAliases
WARNING: No se pudieron obtener los alias del almacen Mozilla / Firefox (unificado): java.lang.IllegalStateException: Se han pedido alias a un almacen no inicializado
de nov. 03, 2020 11:31:23 AM es.gob.afirma.ui.core.jse.JSEUIManager showCertificateSelectionDialog
SEVERE: Se genero un error en el dialogo de seleccion de certificados: java.lang.reflect.InvocationTargetException
de nov. 03, 2020 11:31:23 AM es.gob.afirma.standalone.ui.SignPanelSignTask doSignature
SEVERE: El almacen no contiene ningun certificado que se pueda usar para firmar: es.gob.afirma.keystores.AOCertificatesNotFoundException: No se han encontrado certificados validos en el almacen`

**Comment by alfem** [comment]
Parece que está tirando de librerías de 32 bits:

_library=/usr/lib/i386-linux-gnu/nss/libsoftokn3.so_

Mira de donde sale esa librería, quítala de enmedio y prueba otra vez.

**Comment by dtalens** [comment]
Hola alfem,

He deinstalado diversas librerias nss de 32bits que tenia instaladas con playonlinux (si no recuerdo mal), he dejado solo wine64. Ahora ya encuentra los certificados. Solucionado.

Gracias!!!

**Comment by clawgrip** [comment]
Voy a poner un analizador de ELF para que se ignore el NSS que no sea de la arquitectura adecuada, y siga buscando otras bibliotecas NSS que si valgan, así evitamos estos errores en el futuro.
Muchas gracias.

**Comment by alfem** [comment]
Hombre, con que en el path no ponga "32" igual vale.

**Comment by Immagarcia** [comment]
Me falla en la web de nic peor No en la de la UNI
https://ar.nic.es/sgnd/loginCert.action

Le doy al boton, me abre la aplicacion No me muestra el certificado tal como muestro en  las capturas, pero si abro la aplicación si me aparece.. asi que lo tengo bien instalado de hecho llevo mucos meses firmando documento y ahora que lo necesito para la web de nic No funciona

he probado tambien con el lector de dniE y en la web de la UNi si me loguea con el lector y aqui en nic no

`----
Firefox 82,0
Google chrome Versión 88.0.4324.150

autofirma 1,6,5

Mac os catalina 10.15.7
----
Y en la guia de instalación dice esto:

AutoFirma es compatible con las versiones de OS X Yosemite, El Capitán y Sierra. Los navegadores compatibles son Apple Safari, Google Chrome y Mozilla Firefox.`

![imagen](https://user-images.githubusercontent.com/79018766/107857094-99a0ca00-6e2c-11eb-9230-b2723f03e681.png)
![imagen](https://user-images.githubusercontent.com/79018766/107857099-9e657e00-6e2c-11eb-80af-8cdfab02b441.png)
![imagen](https://user-images.githubusercontent.com/79018766/107857106-a4f3f580-6e2c-11eb-8eda-a334c8645d0c.png)
