### ISSUE TITLE
Saf_19 No hay certificado... etc etc (con  mac actualizado )

### ISSUE THREAD

**Issue by Immagarcia** [ctt-gob-es/clienteafirma#175]
`Me falla en la web de nic peor No en la de la UNI
https://ar.nic.es/sgnd/loginCert.action

Le doy al boton, me abre la aplicacion No me muestra el certificado tal como muestro en las capturas, pero si abro la aplicación si me aparece.. asi que lo tengo bien instalado de hecho llevo mucos meses firmando documento y ahora que lo necesito para la web de nic No funciona

he probado tambien con el lector de dniE y en la web de la UNi si me loguea con el lector y aqui en nic no

`----
Firefox 82,0
Google chrome Versión 88.0.4324.150

autofirma 1,6,5
Mac os catalina 10.15.7

Y en la guia de instalación dice esto:

AutoFirma es compatible con las versiones de OS X Yosemite, El Capitán y Sierra. Los navegadores compatibles son Apple Safari, Google Chrome y Mozilla Firefox.``

![imagen](https://user-images.githubusercontent.com/79018766/107858137-e5567200-6e32-11eb-80a3-a902addd9b78.png)
![imagen](https://user-images.githubusercontent.com/79018766/107858139-e8e9f900-6e32-11eb-92b9-1bed26ddd9e4.png)
![imagen](https://user-images.githubusercontent.com/79018766/107858143-edaead00-6e32-11eb-8807-32861a21a401.png)

**Comment by Immagarcia** [comment]
aquí tenemos mas detalles de mi problema y pruebas https://drive.google.com/file/d/1t-B0zG3ahqppJj6u8mrQ_wXV9Qvkkj2t/view?usp=sharing

**Comment by Immagarcia** [comment]
Despues de borrar cache, de Firefox /chrome.. De eliminar aplicación he instalar de nuevo por tercera vez.. Ni así me funciona

Ya me dan largas.. voy a probar suerte con el DNIE y un lector que tengo por casa

lo último que me dice NIC: Estimada Inma,

El error se suele solucionar limpiando del navegador caché y cookies además de desinstalando el programa de Autofirma e instalándolo de nuevo.

Lamentamos informaros que no podemos damos más soporte del programa Autofirma.

Si necesitas alguna aclaración o realizar una nueva consulta, no dudes en ponerte en contacto con nosotros en esta misma dirección de correo electrónico (ar@dominios.es), a través de nuestros números de Atención al Cliente: 902 450 480 y 912 900 337 o bien mediante chat online disponible en www.chat.dominios.es

**Comment by Immagarcia** [comment]
"C,," 2021-02-13T17:31:20.797056Z 1613237480797 56000 31 es.gob.afirma INFO es.gob.afirma.standalone.configurator.ConfiguratorMacOSX configureSSL 1 Configuracion de NSS 2021-02-13T17:31:20.802391Z 1613237480802 391000 32 es.gob.afirma WARNING es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilitiesOsX configureMacNSS 1 No se puede realizar una carga directa de NSS, se crearan enlaces simbolicos: java.lang.UnsatisfiedLinkError: /Applications/Firefox.app/Contents/MacOS/libsoftokn3.dylib: dlopen(/Applications/Firefox.app/Contents/MacOS/libsoftokn3.dylib, 1): Library not loaded: @executable_path/libnss3.dylib Referenced from: /Applications/Firefox.app/Contents/MacOS/libsoftokn3.dylib Reason: image not found 2021-02-13T17:31:21.027841Z 1613237481027 841000 33 es.gob.afirma INFO es.gob.afirma.standalone.configurator.ConfiguratorMacOSX executeScriptFile 1

**Comment by Immagarcia** [comment]
He actualizad a Big sure.. y el problema/error es otro.. reabro nuevo issue

**Comment by mayask** [comment]
Algún solución para Big Sur y nuevos macs con M1?

**Comment by Immagarcia** [comment]
Hola.. también te falla con el acceso a ar.nic ?

De ser así , al final me los solucionaron los de nic.. trabajando mucho para que mi problema se solucionase y poder trabajar sin problemas
