### ISSUE TITLE
Propiedades de Autofirma por linea de comandos

### ISSUE THREAD

**Issue by landaga** [ctt-gob-es/clienteafirma#181]
Existe alguna forma de que al ejecutar Autofirma por línea de comandos respete las preferencias introducidas en la aplicación de escritorio? 
Necesito firmar ficheros  XML en formato **XAdES Enveloped** y con una Política a medida pero sólo lo consigo si lo hago en la aplicación de escritorio y ésta opción no es muy factible si hay que firmar muchos ficheros.

**Comment by juanjosepablos** [comment]
Duplicado de #187

**Comment by landaga** [comment]
Solucionado en #187
