### ISSUE TITLE
Error compilando clienteafirma, se llama a método que ya no existe

### ISSUE THREAD

**Issue by albfernandez** [ctt-gob-es/clienteafirma#185]
Los métodos "pregSign" y "postSign" en la clase  PAdESTriPhaseSigner se han cambiado par tener un nuevo parámetro "secureMode",

Sin embargo la llamada en el módulo "afirma-server-triphase-signer-core" no se han modificado para pasar ese parámetro y por lo tanto no compilan.

[ERROR] /home/alberto/git/clienteafirma/afirma-server-triphase-signer-core/src/main/java/es/gob/afirma/triphase/signer/processors/PAdESTriPhasePreProcessor.java:[82,37] error: method preSign in class PAdESTriPhaseSigner cannot be applied to given types;
[ERROR]   required: String,byte[],Certificate[],GregorianCalendar,Properties,boolean
[ERROR]   found: String,byte[],X509Certificate[],GregorianCalendar,Properties
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] /home/alberto/git/clienteafirma/afirma-server-triphase-signer-core/src/main/java/es/gob/afirma/triphase/signer/processors/PAdESTriPhasePreProcessor.java:[176,45] error: method postSign in class PAdESTriPhaseSigner cannot be applied to given types;
[ERROR]   required: String,byte[],Certificate[],byte[],PdfSignResult,SignEnhancer,Properties,boolean
[ERROR]   found: String,byte[],X509Certificate[],byte[],PdfSignResult,SignEnhancer,Properties
[ERROR]   reason: actual and formal argument lists differ in length

**Comment by pr-apes** [comment]
@albfernandez, perdona si esto es irrelevante, pero no sé valorarlo yo.

¿Puede ser que la publicación ff0857d2ecbc84946e43a582ab82c1034f927038 haya solucionado el problema?

**Comment by albfernandez** [comment]
Sí, la última versión ya compila correctamente
