### ISSUE TITLE
Autofirmacommandline.exe no procesa el parametro xadesSignFormat=XAdES Enveloped

### ISSUE THREAD

**Issue by AndoniAlonso** [ctt-gob-es/clienteafirma#187]
Hola,
Uno de los requerimientos de firmas de la norma TicketBAI de la CAPV es que el tipo de firma XADES debe ser Enveloped. La opción de utilizar autofirma en su versión command-line es perfecta porque permite especificar todos los requisitos como la política de firma, etc., sin embargo al intentar especificar el formato de firma no funciona. El siguiente comando:

"C:\Program Files\AutoFirma\AutoFirma\AutoFirmaCommandLine.exe" sign -certgui -i "E:\Python\TBAI_QR\Facturas\F21-011.XML" -o "E:\Python\TBAI_QR\Facturas\F21-011_signed.XML" -format xades -xml -config xadesSignFormat="XAdES Enveloped"

No da error pero genera el fichero firmado con el formato XADES Enveloping.
Aunque se utilicen otros alias para el valor del parámetro como "XAdES_Enveloped" o "XAdESEnveloped" sigue sin funcionar.

**Comment by juanjosepablos** [comment]
Ignórame si me equivoco, no lo he utilizado, pero según https://github.com/ctt-gob-es/clienteafirma/blob/master/afirma-simple/src/main/java/es/gob/afirma/standalone/ui/preferences/PreferencesManager.java#L226
es "XAdES Enveloped"

**Comment by AndoniAlonso** [comment]
Hola juanjosepablos,
eso es la primera prueba que he hecho. En ese caso el comando ni siquiera se ejecuta y da error. Es decir cuando un valor de un parámetro tiene un espacio dentro de las opciones 'config=.......' el parser del comando da error.
Ejemplo: 
"C:\Program Files\AutoFirma\AutoFirma\AutoFirmaCommandLine.exe" sign -certgui -i "E:\Python\TBAI_QR\Facturas\F21-011.XML" -o "E:\Python\TBAI_QR\Facturas\F21-011_signed.XML" -format xades -xml -config xadesSignFormat=XAdES Enveloped

devuelve: 
'No se reconoce el parametro Enveloped'

Toma el espacio como separador de parámetros.

**Comment by landaga** [comment]
Hola,
llevo varias semanas intentando lo mismo que tu Andoni y tampoco he conseguido que firme en XAdES Enveloped ni que procese la política de firma que piden en TBAI. Has conseguido tu esto último?
Yo de momento estoy llamando desde mi aplicación a la versión de escritorio de Autofirma pero es un fastidio tener que seleccionar cada xml, firmarlo y guardarlo.....

**Comment by jreverendo** [comment]
Estamos igual, a ver si alguien pone algo de luz.

Gracias

**Comment by jreverendo** [comment]
Creo que lo encontre lo que hay que utilizar es:

 -config "format=XAdES Enveloped"

**Comment by landaga** [comment]
Genial!!!
ya solo nos queda que acepte la política de firma de Batuz

**Comment by landaga** [comment]
Conseguido!!!
-config "format=XAdES Enveloped\npolicyIdentifier=https://www.batuz.eus/fitxategiak/batuz/ticketbai/sinadura_elektronikoaren_zehaztapenak_especificaciones_de_la_firma_electronica_v1_0.pdf\npolicyIdentifierHash=Quzn98x3PMbSHwbUzaj5f5KOpiH0u8bvmwbbbNkO9Es=\npolicyIdentifierHashAlgorithm=http://www.w3.org/2001/04/xmlenc#sha256\npolicyQualifier=https://www.batuz.eus/fitxategiak/batuz/ticketbai/sinadura_elektronikoaren_zehaztapenak_especificaciones_de_la_firma_electronica_v1_0.pdf"

Espero que os sirva

**Comment by jreverendo** [comment]
Para Guipuzcoa seria????

autofirmacommandline.exe sign -i c:\prueba.xml -o c:\pruefirm.xml -store windows -filter subject.contains:XXXXXXXX -config "format=XAdES Enveloped\npolicyIdentifier=https://www.gipuzkoa.eus/ticketbai/sinadura\npolicyIdentifierHash=6NrKAm60o7u62FUQwzZew24ra2ve9PRQYwC21AM6In0=\npolicyIdentifierHashAlgorithm=http://www.w3.org/2001/04/xmlenc#sha256\npolicyQualifier=https://www.gipuzkoa.eus/ticketbai/sinadura"

Si alguien ve alguna cosa que no esta bien agradeceria me lo dijese.

**Comment by landaga** [comment]
Yo lo veo correcto.
LLamada al autofirma, firma, ficheros de entrada y salida, almacen, certificado a utilizar, formato Xades Enveloped y política de firma ajustada a lo exigido por la hacienda correpondiente.
Me estaba volviendo loco con este asunto pero estaba seguro que había una forma de conseguirlo...

**Comment by jreverendo** [comment]
> Yo lo veo correcto.
> LLamada al autofirma, firma, ficheros de entrada y salida, almacen, certificado a utilizar, formato Xades Enveloped y política de firma ajustada a lo exigido por la hacienda correpondiente.
> Me estaba volviendo loco con este asunto pero estaba seguro que había una forma de conseguirlo...

Una pregunta offtopic los 100 primeros caracteres que hay que guardar de la firma de la factura para rellenar los datos de factura anterior de que campo del XML hay que pillarlos.

**Comment by AndoniAlonso** [comment]
> Una pregunta offtopic los 100 primeros caracteres que hay que guardar de la firma de la factura para rellenar los datos de factura anterior de que campo del XML hay que pillarlos.

Del campo SignatureValue:
"SignatureValueFirmaFacturaAnterior | Alfanumérico(100) | Primeros cien caracteres del campoSignatureValue del fichero TicketBAI de lafactura anterior"

**Comment by AndoniAlonso** [comment]
> Conseguido!!!
> -config "format=XAdES Enveloped\npolicyIdentifier=[https://www.batuz.eus/fitxategiak/batuz/ticketbai/sinadura_elektronikoaren_zehaztapenak_especificaciones_de_la_firma_electronica_v1_0.pdf\npolicyIdentifierHash=Quzn98x3PMbSHwbUzaj5f5KOpiH0u8bvmwbbbNkO9Es=\npolicyIdentifierHashAlgorithm=http://www.w3.org/2001/04/xmlenc#sha256\npolicyQualifier=https://www.batuz.eus/fitxategiak/batuz/ticketbai/sinadura_elektronikoaren_zehaztapenak_especificaciones_de_la_firma_electronica_v1_0.pdf](https://www.batuz.eus/fitxategiak/batuz/ticketbai/sinadura_elektronikoaren_zehaztapenak_especificaciones_de_la_firma_electronica_v1_0.pdf%5CnpolicyIdentifierHash=Quzn98x3PMbSHwbUzaj5f5KOpiH0u8bvmwbbbNkO9Es=%5CnpolicyIdentifierHashAlgorithm=http://www.w3.org/2001/04/xmlenc#sha256%5CnpolicyQualifier=https://www.batuz.eus/fitxategiak/batuz/ticketbai/sinadura_elektronikoaren_zehaztapenak_especificaciones_de_la_firma_electronica_v1_0.pdf)"
> 
> Espero que os sirva

jreverendo y landaga, ¡muchisísimas gracias por vuestra aportación! La verdad es que es una impotencia terrible saber que el aplicativo tiene la potencia para generar la firma y no ser capaz de conseguir que "trague".  :-)

**Comment by AndoniAlonso** [comment]
Con las instrucciones que se han dado doy por cerrada esta cuestión. 
Muchas gracias por las aportaciones!

**Comment by joseluisartensio** [comment]
Parece que para firmar por línea de comandos, el parámetro pasado a -config para firmar como format=XAdES Enveloped no funciona bajo sistemas linux. 

En AutoFirmaCommandLine.exe sign funciona perfectamente pero los mismos parámetros ejecutados en /usr/bin/AutoFirma sign, devuelve error de "No se reconoce el parametro Enveloped"

Alguien ha conseguido una firma por línea de comandos en linux con XAdES Enveloped?
