### ISSUE TITLE
Fallo al iniciar AutoFirma en la clase java.awt.Toolkit

### ISSUE THREAD

**Issue by anerodata** [ctt-gob-es/clienteafirma#212]
Hola, estoy teniendo un problema a la hora de iniciar AutoFirma en Ubuntu 20.04. En consola el error es el siguiente:

```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
	at java.desktop/java.awt.Color.<clinit>(Color.java:275)
	at es.gob.afirma.standalone.LookAndFeelManager.<clinit>(LookAndFeelManager.java:60)
	at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:549)
```
Cuando hago `ldd /usr/bin/java`. La respuesta es la siguiente:
```
linux-vdso.so.1 (0x00007ffdd4df5000)
	libjli.so => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb15f2ec000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb15f4f9000)
```
¿Puede ser que Java no esté encontrando `libjli.so` y necesite enrutarlo o instalarlo? No tengo mucha experiencia en distribuciones Linux, por eso cualquier pista me ayudaría mucho.

Saludos y gracias

**Comment by Wolf20** [comment]
¿Que versión de Java usas?

**Comment by anerodata** [comment]
La versión 11:

```
openjdk version "11.0.11"
```

Claro, parece que necesito tener la 8, no? En su día, cuando instalé Autofirma y las dependencias instalé la 8, pero al correr las actualizaciones es posible que se haya actualizado Java.

**Comment by Wolf20** [comment]
Intenta ejecutar Java 8 a ver si así funciona, si sigue fallando habría que ver que pasa, es la versión de autofirma 1.6.5 ¿Verdad?

**Comment by anerodata** [comment]
De acuerdo, gracias. 

Sí, al hacer `apt list` y filtrar:

```
autofirma/now 1.6.5
```

**Comment by anerodata** [comment]
Gracias! Ya está solucionado. Ahora el programa se ejecuta correctamente. La cuestión es que creo recordar haber instalado en su día la versíon 8 de Java, tal y como figura en la documentación. Creo que se me ha podido actualizar en algún momento. En cualquier caso, muchas gracias por la ayuda y saludos.

**Comment by Wolf20** [comment]
Te recomiendo para asegurarte de que siempre se ejecute con java8 que cambies el lanzador de autofirma, búscalo con whereis AutoFirma, y cuando lo edites verás qué tiene dos líneas de código, para que la próxima vez se ejecute en vez de usar /usr/bin/java usa el path al java 8 que será algo como /usr/lib/jvm/java8/bin/java

**Comment by anerodata** [comment]
Muchas gracias!
