### ISSUE TITLE
DNIs ofuscados siempre en versión 1.7

### ISSUE THREAD

**Issue by pr-apes** [ctt-gob-es/clienteafirma#213]
@Gamuci,

no sé si es por 1a8bf282ccf31c08570e2c73b8103af552480a89, pero acabo de instalar la versión 1.7 (64bit) en dos ordenadores y es imposible hacer una firma visible en la que se muestre el DNI completo.

Aunque esté desactivada la opción correspondiente, la ofuscación de DNI sale siempre.

![ofusca](https://user-images.githubusercontent.com/51094960/125591110-d318f48d-0fcb-43c3-8fe3-f5b634a9f0d0.png)

Como comentario, no acabo de entender la utilidad de la ofuscación si los certificados luego salen con el DNI completo. La utilidad así es mínima.

Muchas gracias.

**Comment by Wolf20** [comment]
¿Es posible que no estes haciendo el campo de firma lo suficientemente grande? Si no es lo suficientemente grande autofirma automaticamente recorta aquello que no entra en vez de ajustar el tamaño automaticamente a si que puede que el mensaje se vea recortado y falte. yo me fijaria mucho en la previsualizacion de la firma visible a ver si esta el mensaje completo

**Comment by pr-apes** [comment]
Muchas gracias, @Wolf20.

Acabo de hacer un campo de firma gigante, imposible que no quepa.

El resultado es el mismo, el DNI está ofuscado.

**Comment by pr-apes** [comment]
Solucionado en versión 1.7.1.
