### ISSUE TITLE
Autofirma no parece funcionar con el nuevo DNIe (Sept 2021) (Debian 11)

### ISSUE THREAD

**Issue by emunicio** [ctt-gob-es/clienteafirma#216]
Hola, estoy probando a firmar unos documentos, pero Autofirma no puede acceder a los certificados del DNIe.
Estoy usando Debian 11, y las aplicaciones de Cl@ve funcionan bien a través de Firefox, pero no en Autofirma.
He probado con java 8 y java 11 y parece existir el mismo problema.

Estos son los últimos logs que tengo antes del error:

> <record>
>   <date>2021-09-02T15:16:51.726736Z</date>
>   <millis>1630595811726</millis>
>   <nanos>736000</nanos>
>   <sequence>16</sequence>
>   <logger>es.gob.afirma</logger>
>   <level>INFO</level>
>   <class>es.gob.afirma.keystores.AOKeyStoreManager</class>
>   <method>init</method>
>   <thread>26</thread>
>   <message>Inicializamos el almacen de tipo: DNIe y tarjetas FNMT-TIF</message>
> </record>

> <record>
>   <date>2021-09-02T15:16:51.980507Z</date>
>   <millis>1630595811980</millis>
>   <nanos>507000</nanos>
>   <sequence>17</sequence>
>   <logger>es.gob.afirma</logger>
>   <level>INFO</level>
>   <class>es.gob.afirma.keystores.AOKeyStoreManagerHelperFullJava</class>
>   <method>init</method>
>   <thread>26</thread>
>   <message>Cargando KeyStore 100% Java para DNIe y tarjetas FNMT-TIF</message>
> </record>

> <record>
>   <date>2021-09-02T15:16:52.024117Z</date>
>   <millis>1630595812024</millis>
>   <nanos>117000</nanos>
>   <sequence>18</sequence>
>   <logger>es.gob.jmulticard</logger>
>   <level>INFO</level>
>   <class>es.gob.jmulticard.card.dnie.DnieFactory</class>
>   <method>getDnie</method>
>   <thread>26</thread>
>   <message>Detectado DNIe 3.0</message>
> </record>

> <record>
>   <date>2021-09-02T15:16:52.722865Z</date>
>   <millis>1630595812722</millis>
>   <nanos>865000</nanos>
>   <sequence>19</sequence>
>   <logger>es.gob.jmulticard</logger>
>   <level>WARNING</level>
>   <class>es.gob.jmulticard.card.iso7816four.Iso7816FourCard</class>
>   <method>readBinaryComplete</method>
>   <thread>26</thread>
>   <message>Se ha intentado una lectura fuera de los limites del fichero, se devolvera lo leido hasta ahora: es.gob.jmulticard.card.iso7816four.OffsetOutsideEfException: Parametro(s) incorrecto(s) P1-P2 (6B00). APDU de origen: 00-B0-06-82-EE</message>
> </record>

> <record>
>   <date>2021-09-02T15:16:53.166231Z</date>
>   <millis>1630595813166</millis>
>   <nanos>231000</nanos>
>   <sequence>20</sequence>
>   <logger>es.gob.afirma</logger>
>   <level>SEVERE</level>
>   <class>es.gob.afirma.keystores.AOKeyStoreManager</class>
>   <method>getCertificate</method>
>   <thread>26</thread>
>   <message>Error intentando recuperar el certificado con el alias 'CertAutenticacion', se devolvera null: java.security.ProviderException: es.gob.jmulticard.card.CryptoCardException: Error en el establecimiento del canal seguro de PIN: es.gob.jmulticard.apdu.connection.ApduConnectionException: Error al verificar la cadena de certificados del controlador: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado de la CA intermedia de Terminal: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado. Se obtuvo el error: 6A-80: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado. Se obtuvo el error: 6A-80: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado de la CA intermedia de Terminal: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado. Se obtuvo el error: 6A-80:
> 

Alguna idea de como solucionar esto?
Un saludo y muchas gracias

**Comment by SergioSuarezDev** [comment]
A mi en mac, con el nuevo dni, no me reconoce tampoco el certificado, ademas no me deja exportarlo de firefox para poder importarselo a la app :(

**Comment by branigan** [comment]
> Actualizo mi comentario: la versión para MacOSx y Linux 1.6.5 NO he conseguido que funcione con el DNIe 4.0, pero la versión 1.7.1 de Windows sí. Y la versión de Windows se puede usar en MacOS. Resulta que después de instalar la aplicación en Windows, se puede localizar el archivo AutoFirma.exe en el directorio de instalación. Este archivo es en realidad un archivo JAR y sólo hay que cambiarle la extensión para usarlo en MacOSX o Linux.

He conseguido que me pille el DNI 4.0 con la solución que das, pero al ir a firmar desde Firefox me da el error SAF_16. Los certificados están instalados y aceptados, y el proxy lo tengo desactivado. Tu lo has hecho con Firefox o con otro navegador ?

**Comment by enriqueartal** [comment]
Todavía no he comprobado si actualizando en la comisaría funciona, a mé me fallaba tanto con firefox como por la aplicación (en linux)

**Comment by joatumas** [comment]
> > Actualizo mi comentario: la versión para MacOSx y Linux 1.6.5 NO he conseguido que funcione con el DNIe 4.0, pero la versión 1.7.1 de Windows sí. Y la versión de Windows se puede usar en MacOS. Resulta que después de instalar la aplicación en Windows, se puede localizar el archivo AutoFirma.exe en el directorio de instalación. Este archivo es en realidad un archivo JAR y sólo hay que cambiarle la extensión para usarlo en MacOSX o Linux.
> 
> He conseguido que me pille el DNI 4.0 con la solución que das, pero al ir a firmar desde Firefox me da el error SAF_16. Los certificados están instalados y aceptados, y el proxy lo tengo desactivado. Tu lo has hecho con Firefox o con otro navegador ?

Usando el truco del trasplante de la versión Windows a MacOSx el DNI 4.0 a mi me ha funcionado con todos los navegadores, incluyendo Firefox.

**Comment by merdallada** [comment]
Yo no he conseguido que funcione la autofirma 1.6.5 para Linux. Mis datos:

```
Operating System: Ubuntu 20.04.2 LTS
Kernel: Linux 5.4.0-81-generic
Architecture: x86-64
```

He seguido pasos detallados aquí: https://github.com/ctt-gob-es/clienteafirma/issues/145#issuecomment-845585328 y al igual que este usuario, no he podido hacer que funcione. Java 8 correctamente instalado.

Mis errores:

```
Nov 20, 2021 12:39:38 PM es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager init
INFO: El almacen externo 'New PKCS#11 Module' ha podido inicializarse, se anadiran sus entradas y se detiene la carga del resto de almacenes
Nov 20, 2021 12:39:38 PM es.gob.afirma.standalone.SimpleAfirma setKeyStoreManager
INFO: Establecido KeyStoreManager: Gestor de almacenes de claves Mozilla / Firefox (unificado) con nombre Mozilla / Firefox (unificado)
Nov 20, 2021 12:39:38 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: Cargando plugins
Nov 20, 2021 12:39:38 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: Iniciando entorno grafico
Nov 20, 2021 12:39:40 PM es.gob.afirma.keystores.AOKeyStoreManager init
INFO: Inicializamos el almacen de tipo: DNIe y tarjetas FNMT-TIF
Nov 20, 2021 12:39:40 PM es.gob.afirma.keystores.AOKeyStoreManagerHelperFullJava init
INFO: Cargando KeyStore 100% Java para DNIe y tarjetas FNMT-TIF
Nov 20, 2021 12:39:40 PM es.gob.jmulticard.card.dnie.DnieFactory getDnie
INFO: Detectado DNIe 3.0
Nov 20, 2021 12:39:40 PM es.gob.jmulticard.card.iso7816four.Iso7816FourCard readBinaryComplete
WARNING: Se ha intentado una lectura fuera de los limites del fichero, se devolvera lo leido hasta ahora: es.gob.jmulticard.card.iso7816four.OffsetOutsideEfException: Parametro(s) incorrecto(s) P1-P2 (6B00). APDU de origen: 00-B0-07-70-B6
Nov 20, 2021 12:39:40 PM es.gob.afirma.keystores.AOKeyStoreManager getCertificate
SEVERE: Error intentando recuperar el certificado con el alias 'CertAutenticacion', se devolvera null: java.security.ProviderException: es.gob.jmulticard.card.CryptoCardException: Error en el establecimiento del canal seguro de PIN: es.gob.jmulticard.apdu.connection.ApduConnectionException: Error al verificar la cadena de certificados del controlador: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado de la CA intermedia de Terminal: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado. Se obtuvo el error: 6A-80: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado. Se obtuvo el error: 6A-80: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado de la CA intermedia de Terminal: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado. Se obtuvo el error: 6A-80: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado. Se obtuvo el error: 6A-80: Error al verificar la cadena de certificados del controlador: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado de la CA intermedia de Terminal: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado. Se obtuvo el error: 6A-80: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado. Se obtuvo el error: 6A-80: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado de la CA intermedia de Terminal: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado. Se obtuvo el error: 6A-80: es.gob.jmulticard.apdu.connection.cwa14890.SecureChannelException: Error en la verificacion del certificado. Se obtuvo el error: 6A-80
Nov 20, 2021 12:39:40 PM es.gob.afirma.standalone.SimpleKeyStoreManager getKeyStore
SEVERE: No se ha podido inicializar el controlador 100% Java del DNIe: java.lang.NullPointerException
Nov 20, 2021 12:39:56 PM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'TimesNewRomanPSMT'
Nov 20, 2021 12:40:00 PM es.gob.afirma.standalone.ui.pdf.SignPdfDialog positionSelected
INFO: Propiedades establecidas mediante GUI: {layer2Text=Firmado por $$SUBJECTCN$$ el día $$SIGNDATE=dd/MM/yyyy$$ con un certificado emitido por $$ISSUERCN$$, layer2FontFamily=0, signaturePositionOnPageUpperRightY=197, signaturePositionOnPageUpperRightX=498, layer2FontSize=12, layer2FontStyle=0, signaturePositionOnPageLowerLeftY=94, signaturePositionOnPageLowerLeftX=304, signaturePage=1, layer2FontColor=black}
Nov 20, 2021 12:40:04 PM es.gob.afirma.standalone.ui.SignPanelSignTask doSignature
SEVERE: Ocurrio un error al extraer la clave privada del certificiado seleccionado: java.security.ProviderException: Token has been removed
```

**Comment by fmrtn** [comment]
Para hacerlo funcionar en Debian 11:

- En Firefox Preferencias -> Privacidad y Seguridad -> Dispsitivos de seguridad

Quitar la biblioteca ` /usr/lib/libpkcs11-fnmtdnie.so` y cargar en su lugar `/usr/lib/x86_64-linux-gnu/pkcs11/opensc-pkcs11.so`

Aparece un error al iniciar, pero luego permite firmar documentos con el DNIe

*Previamente tenía instalados los paquetes pcsc-tools pcscd opensc-pkcs11*

**Comment by rdft4e** [comment]
> Para hacerlo funcionar en Debian 11:
> 
>     * En Firefox Preferencias -> Privacidad y Seguridad -> Dispsitivos de seguridad
> 
> 
> Quitar la biblioteca ` /usr/lib/libpkcs11-fnmtdnie.so` y cargar en su lugar `/usr/lib/x86_64-linux-gnu/pkcs11/opensc-pkcs11.so`
> 
> Aparece un error al iniciar, pero luego permite firmar documentos con el DNIe
> 
> _Previamente tenía instalados los paquetes pcsc-tools pcscd opensc-pkcs11_

esto es lo único que me funcionó. Probablemente también hay que desactivar el multicard (control P en autofirma).

**Comment by rgvilla** [comment]
Yo tengo un DNI 3.0, pero me ha llevado casi 4 horas hacer que funcione AutoFirma.
Os dejo lo que yo he hecho:

Instalación en Linux Mint 20.3

1.Instalar la versión 1.6.5 que es la única disponible en linux

2. Descargar la versión 1.7.1 de Windows

3. Descomprimir. Nos sale el ejecutable AutoFirma.exe y lo renombramos como AutoFirma.jar

4. Hacemos una copia de seguridad de /usr/lib/AutoFirma/AutoFirma.jar y lo sustituimos por el nuevo. Le damos los permisos del anterior.

5. Verificar que solo tenemos un perfil en firefox, y eliminar los duplicados si hubiese varios.

/usr/bin/firefox -p

6. Arrancar Autofirma y en Herramientas (Ctrl+P) seleccionar reiniciar configuracion.

7. Ya se pueden firmar documentos con DNIe y con FNMT.

**Comment by PabloCastellano** [comment]
@rgvilla ¡Muchas gracias! Hoy me he encontrado con este problema también y siguiendo tus instrucciones lo acabo de conseguir. :raised_hands: 

Es muy lamentable el estado en el que la Administración mantiene este proyecto. En mi caso es un disgusto tras otro. Tuve que renovar mi DNI 3.0 porque fui un afortunado poseedor de uno de los 19 millones de DNIs invalidados en 2020. [La noticia para el que no la conozca](https://www.elconfidencial.com/espana/2020-07-15/ccoo-error-dni-certificados-digitales-falta-personal_2681807/). Necesitaba hacer un trámite y no funcionaba el certificado del DNIe, quizás había olvidado la clave así que fui a comisaría a cambiarla y allí me enteré de que mi chip estaba "defectuoso" así que encima me tocó pagar a mí el carnet nuevo.

El DNI 4.0 empezó a expedirse en agosto, y sin saberlo me había tocado otra vez la lotería: hoy necesito firmar digitalmente un documento y este modelo aún no está soportado en la versión de AutoFirma disponible para linux (1.6.5). Solo Windows tiene disponible la versión 1.7.1, que sí funciona con DNI 4.0, pero después de 5 meses de que se expide solamente este DNI ningún responsable ha reempaquetado un paquete deb. Así que he perdido inútilmente mi tiempo esta tarde cuando la solución es **trivial** porque encima AutoFirma está hecho en Java. ¿Pero es que no hay nadie al volante? ¿Por qué este maltrato constante a los ciudadanos?

Volviendo al tema, @rgvilla solo quería añadir un par de puntos extra que he tenido que hacer además de los tuyos para encontrar el AutoFirma.exe:

3.1. Descomprime `AutoFirma64.zip` y extrae `AutoFirma_64_v1_7_1_installer.exe`
3.2. Descomprime `AutoFirma_64_v1_7_1_installer.exe` y extrae `AutoFirma.exe` desde el directorio `$_9_`

![imagen](https://user-images.githubusercontent.com/73274/151722408-3a1040ba-a478-48d7-b77c-1f079af5d6bd.png)

Siendo honestos, me ha sorprendido que se pueda lanzar `java -jar AutoFirma.exe`. No me esperaba que funcionara esta forma de lanzar con java ejecutables PE32 de Windows:

```
$ file AutoFirma.exe 
AutoFirma.exe: PE32 executable (GUI) Intel 80386 (stripped to external PDB), for MS Windows
```

**Comment by joatumas** [comment]
La verdad es que es lamentable que tengamos que ir haciendo chapuzas cuando la solución es trivial para el desarrollador y/o el mantenedor de los paquetes.
Para la versión de MacOSX ya hace tiempo que hay blogs explicando como actualizar la versión de la JVM viejuna que incluyen con el paquete. Lo de que se pueda usar la última versión de Windows en otras plataformas y no se dignen a actualizar los paquetes ya es de traca.

Por cierto, para los que hablan de cargar el módulo pkcs11 adecuado en firefox, decir que aunque eso funciona, no lo hace en todos los escenarios. Me he encontrado varias aplicaciones en las que AutoFirma es la única opción, además de que diría que AutoFirma también funciona (cuando funciona) en todos los escenarios en los que se puede usar el módulo de Firefox.

**Comment by PabloCastellano** [comment]
A falta de algún anuncio oficial, os comunico que hace unas horas han actualizado la versión disponible a la 1.7.1, donde funciona el DNIe 4.0 sin hacer nada más (no hay que deshabilitar JMultiCard tampoco).

Creo que se puede cerrar este issue :+1:

![image](https://user-images.githubusercontent.com/73274/152615734-ead3f878-80b5-4d7f-860d-505ade506484.png)

**Comment by merdallada** [comment]
Buenas!

Efectivamente la versión 1.7.1, funciona perfectamente en Linux.  Podeis cerrar el topic

**Comment by enriqueartal** [comment]
Con el último DNI electrónico (obtenido hoy) tanto en la aplicación como en firefox llego hasta el final pero al elegir firmar con el dni tengo un error saf:09 en firefox y en la terminal donde lanza autofirma me sale entre otras cosas

es.gob.afirma.core.AOException: Error durante la firma PAdES: es.gob.afirma.core.AOException: Error al inicializar la firma con la clave privada: java.security.InvalidKeyException: No installed provider supports this key: sun.security.pkcs11.P11Key$P11PrivateKey

**Comment by emunicio** [comment]
Hola, si, con la nueva versión también funciona (Debian bullseye), así que ya se puede cerrar la incidencia.

Gracias
