### ISSUE TITLE
SignaturePolicyIdentifier xades-enveloped

### ISSUE THREAD

**Issue by gaizkaurd** [ctt-gob-es/clienteafirma#264]
Hola.

Estoy intentando utilizar clienteafirma para enviar facturas al servicio TICKETBAI, he conseguido firmar documentos mediante este comando.

`java -jar AutoFirma.jar sign -i file.xml -o file-firmado.xml -store pkcs12:certificado.p12 -password xxxx -filter certificado.p12 -format xades -xml -config "format=XAdES Enveloped"`

Sin embargo, necesito añadir el SignaturePolicyIdentifier, el cual he conseguido añadir mediante la interfaz gráfica, sin embargo, no he encontrado documentación a cerca del CLI. 

 `-config extraParams	 (Properties en texto plano con la configuracion de la operacion)`

Supongo que se hará mediante ese argumento, pero no he conseguido más información.

¿Cómo podría especificar la política?
![Captura de Pantalla 2022-06-11 a las 20 26 03](https://user-images.githubusercontent.com/24901613/173200406-861bcabd-94e1-4339-98d9-7ca72b248594.png)

Muchas gracias, un saludo!

**Comment by Gamuci** [comment]
Buenos días:

Sí, sería a través de la opción -config. En esta le debes pasar los parámetros y sus valores como si fuesen un properties de Java en texto plano:

- config "clave1=valor1\nclave2=valor2\nclave3=valor3..."

Las claves y los valores que se le pueden configurar están en el manual del integrador de AutoScript, aunque en el código de la nueva versión se pueden encontrar estos valores en la ayuda integrada de la propia aplicación. Dejo un enlace al HTML (hay que descargarlo para verlo correctamente):

https://raw.githubusercontent.com/ctt-gob-es/clienteafirma/master/afirma-simple/src/main/resources/help/Spanish.lproj/pgs/LineaComandos.html

Las claves para configurar los parámetros de la política de firma son: policyIdentifier, policyIdentifierHash, policyIdentifierHashAlgorithm, policyQualifier y policyDescription.

**Comment by gaizkaurd** [comment]
> Buenos días:
> 
> Sí, sería a través de la opción -config. En esta le debes pasar los parámetros y sus valores como si fuesen un properties de Java en texto plano:
> 
> * config "clave1=valor1\nclave2=valor2\nclave3=valor3..."
> 
> Las claves y los valores que se le pueden configurar están en el manual del integrador de AutoScript, aunque en el código de la nueva versión se pueden encontrar estos valores en la ayuda integrada de la propia aplicación. Dejo un enlace al HTML (hay que descargarlo para verlo correctamente):
> 
> https://raw.githubusercontent.com/ctt-gob-es/clienteafirma/master/afirma-simple/src/main/resources/help/Spanish.lproj/pgs/LineaComandos.html
> 
> Las claves para configurar los parámetros de la política de firma son: policyIdentifier, policyIdentifierHash, policyIdentifierHashAlgorithm, policyQualifier y policyDescription.

Buenos días, muchas gracias por la respuesta.

Me gustaría hacerle una pregunta a cerca de la integración de autoafirma. Como he mencionado antes estoy intentando hacer una aplicación para enviar facturas al servicio ticketbai.

Habría alguna forma de integrar autoafirma en mi código de java directamente,  o debería hacer que la firma se realice siempre por linea de comandos? ya que quiero que la firma la haga el servidor.

Muchas gracias y un saludo.
