### ISSUE TITLE
AutoFirma no detecta las librerías apropiadas del sistema en Fedora (64 bit)

### ISSUE THREAD

**Issue by ssaavedra** [ctt-gob-es/clienteafirma#27]
En Fedora (desde hace muchas releases), las librerías de 64 bits se encuentran en /usr/lib64 y las de 32 bits en /usr/lib, por lo que en Fedora de 64 bits (con Firefox de 64 bits) se detecta incorrectamente que debería de estar utilizándose la biblioteca NSS de 32 bits, ya que nunca se busca en lib64.

Debería de incluirse un chequeo preferentemente de `/usr/lib${Platform.getArch()}` antes de utilizar `/usr/lib`, para que esto funcione en la mayoría de Unixes, o inspeccionar el valor del java.library.path y utilizarlo como referencia (ya que debería de haberse populado apropiadamente por la JVM).

Yo he conseguido firmar con firma trifásica en Fedora 27 añadiendo a la lista de búsqueda del NSS lib en primer lugar /usr/lib64 y compilando a mano los módulos con -DskipTests (porque uno de los tests falla con "plataforma incorrecta" como si Linux no estuviese soportado), con el certificado de la FNMT, Firefox 59 y teniendo en ~/.pki/nssdb los ficheros `cert9.db` `key4.db` y `pkcs11.txt`.

**Comment by tururut** [comment]
Como ya comenta @ssaavedra, en Fedora las librerías NSS dan problemas, puesto que las de 32 y 64 bits no se encuentran en los mismos directorios que en Debian/Ubuntu. La cuestión es que al menos desde Fedora 27 (convirtiendo el deb a RPM con alien) hasta el recién salido Fedora 30 con autofirma-1.6.5 (que ya incluye un RPM) esto ha dado problemas. En el commit [eeef77b](https://github.com/ctt-gob-es/clienteafirma/commit/eeef77bc7a422f94774d26da0c1616275b421dcc) parece que se intenta resolver esto, pero la cuestión es que la manera de buscar las librerías parece que no sigue un criterio claro. Puesto que el RPM instala autofirma en /usr/lib64, entiendo que el objetivo es que funcione correctamente, como mínimo, en los sistemas de 64 bits que utilizan RPM (CentOS/RHEL, Fedora, SuSE). Si se quiere conseguir esto, la manera de buscar las librerías no es apropiada por varios motivos:

- La lista de directorios está metida directamente en el código y no se usan propiedades ni ficheros de configuración, por lo que no se puede cambiar sin recompilar.

- Se deberían buscar en primer lugar los directorios de 64 bits, luego los que pueden contener mezcla de arquitecturas y finalmente los directorios de 32 bits. Eso si se quiere hacer una lista estática, porque la lista podría ser dinámica consultando en tiempo de ejecución la arquitectura del sistema sobre el que se ejecuta el código. Tal como está ahora no sigue un orden determinado y si por mala suerte encuentra la librería de 32 bits antes que la de 64 bits, el programa no funciona. De hecho, con el commit que he mencionado antes, se pone más arriba en la lista /usr/lib64, pero /lib sigue estando antes, por lo que, en mi caso específico (Fedora 30 x86_64), me sigue encontrando las librerías incorrectas. Además, ha quedado el /usr/lib64 repetido al final, donde no tiene sentido que se encuentre, porque ya se habrán explorado todos los directorios de 32 bits.

- La lista de directorios en sí supongo que tendrá sus motivos para ser esa, pero resulta curiosa como mínimo. Se busca en /opt/fedora-ds/clients/lib (¿Fedora Directory Server?), en /opt/google/chrome (mi instalación de Chrome no tiene ninguna de las 4 librerías buscadas ahí; de hecho, solo hay dos librerías del sistema de DRM Widevine), en /usr/lib/thunderbird (¿y por qué no en /usr/lib64/thunderbird?), etc. En fin, se diría que hace falta una revisión de qué plataformas se quieren soportar y dónde están las librerías en cada una.

- Se buscan distintas versiones de Firefox en /usr/lib/firefox-* y /opt/firefox-*. El problema es que el código busca "firefox-" seguido de una cadena y luego comprueba que esta sea un entero, en cuyo caso se ordena la lista como una lista de cadenas y se devuelve la mayor. Esto puede fallar al pasar de la versión 60.0.9 a la 60.0.10, por poner un ejemplo, pero mi sospecha es que falla siempre, porque se comprueba que la cadena contiene un entero usando "Integer.getInteger(firefoxDirectories.get(i));", que en realidad busca una propiedad con el nombre que recibe como parámetro y devuelve su valor como un entero (en este caso siempre devolverá null, ya que no existen propiedades con nombres de path), en lugar de utilizar Integer.parseInt, que sí haría la conversión. Además, si no se encuentra ninguna versión de Firefox, se devuelve la cadena vacía, que se concatena con el path correspondiente en la lista, por lo que, si no hay versiones de Firefox en /usr/lib o en /opt, resulta que se busca en /usr/lib/firefox- y /opt/firefox- (terminando en guion los dos).

- El código que intenta cargar la librería hace un "catch (final Exception e)" para poder continuar probando otras librerías si una no carga. Lo que pasa es que si no carga por ser de 32 bits (u otros motivos, como que no exista el fichero), lo que devuelve System.load() no es una java.lang.Exception sino un java.lang.UnsatisfiedLinkError, con lo que el programa da error. De hecho, solamente con que se arreglara esto, ya sería un paso importante, puesto que al menos iría probando librerías hasta encontrar una que no falle, en lugar de lo que hace ahora, que es ir buscando librerías hasta encontrar una y ya no se pasa de ahí (o bien porque funciona o bien porque da error y se interrumpe la ejecución).

Para muestra, lo que ocurre después de la instalación:
```
$ autofirma
may 01, 2019 9:57:37 PM es.gob.afirma.standalone.ProxyUtil clearJavaProxy
INFORMACIÓN: No se usara Proxy para las conexiones de red
may 01, 2019 9:57:37 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: No se buscaran nuevas versiones de la aplicacion
may 01, 2019 9:57:37 PM es.gob.afirma.standalone.SimpleAfirma printSystemInfo
INFORMACIÓN: AutoFirma 1.6.5
Resolucion DPI de pantalla: 0
Sistema operativo: Linux
Version del SO: 5.0.9-301.fc30.x86_64
Version de Java: 1.8.0_201
Arquitectura del JRE: 64
Java Vendor: Oracle Corporation
Localizacion por defecto: es_ES
Tamano actual en memoria: 236MB
Tamano maximo de memoria: 3499MB
Memoria actualmente libre: 177MB
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
may 01, 2019 9:57:37 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: Apertura como herramienta de escritorio
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
may 01, 2019 9:57:38 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: Se intenta una precarga temprana de NSS
OpenJDK 64-Bit Server VM warning: You have loaded library /usr/lib/libsqlite3.so.0.8.6 which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/lib/libsqlite3.so.0.8.6: /usr/lib/libsqlite3.so.0.8.6: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilitiesUnix.getNSSLibDirUnix(MozillaKeyStoreUtilitiesUnix.java:75)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.getSystemNSSLibDir(MozillaKeyStoreUtilities.java:251)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNSS(MozillaKeyStoreUtilities.java:699)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.getNssProvider(NssKeyStoreManager.java:122)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.init(NssKeyStoreManager.java:59)
	at es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager.init(MozillaUnifiedKeyStoreManager.java:72)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getNssKeyStoreManager(AOKeyStoreManagerFactory.java:511)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getMozillaUnifiedKeyStoreManager(AOKeyStoreManagerFactory.java:542)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getAOKeyStoreManager(AOKeyStoreManagerFactory.java:133)
	at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:646)
```

Como workaround temporal, puedo hacer esto (como root):
```
ln -s /usr/lib64 /opt/firefox-
```
Entonces el resultado es correcto:
```
$ autofirma
may 01, 2019 10:02:33 PM es.gob.afirma.standalone.ProxyUtil clearJavaProxy
INFORMACIÓN: No se usara Proxy para las conexiones de red
may 01, 2019 10:02:33 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: No se buscaran nuevas versiones de la aplicacion
may 01, 2019 10:02:33 PM es.gob.afirma.standalone.SimpleAfirma printSystemInfo
INFORMACIÓN: AutoFirma 1.6.5
Resolucion DPI de pantalla: 0
Sistema operativo: Linux
Version del SO: 5.0.9-301.fc30.x86_64
Version de Java: 1.8.0_201
Arquitectura del JRE: 64
Java Vendor: Oracle Corporation
Localizacion por defecto: es_ES
Tamano actual en memoria: 236MB
Tamano maximo de memoria: 3499MB
Memoria actualmente libre: 177MB
may 01, 2019 10:02:33 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: Apertura como herramienta de escritorio
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
may 01, 2019 10:02:33 PM es.gob.afirma.standalone.SimpleAfirma main
INFORMACIÓN: Se intenta una precarga temprana de NSS
may 01, 2019 10:02:33 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNSS
INFORMACIÓN: Configuracion de NSS para SunPKCS11:
name=NSSCrypto-AFirma
library=/usr/lib64/libsoftokn3.so
attributes=compatibility
slot=2
showInfo=false
...
```

**Comment by ssaavedra** [comment]
Interesante workaround.

Coincido con el análisis que haces del código, y que si se quiere insistir en tener la lógica de cargar bibliotecas y no delegarla a la JVM (por ejemplo, utilizando System.loadLibrary en lugar de System.load) para soportar ciertas arquitecturas a las que no se quiera relegar el problema a upstream (al final es inevitable en ciertos casos tener que lidiar con legacy de un tipo u otro), al menos tendría que implementarse una lógica que sea correcta para las plataformas soportadas.

**Comment by ssaavedra** [comment]
Después de tiempo y de haber implementado una lógica que considero apropiada para compatibilidad con múltiples sistemas en #91 no he tenido feedback ni por parte de @Gamuci o @clawgrip ni por parte de usuarios que hayan dicho que se les haya roto el proceso de firma.
Yo estoy utilizando AutoFirma con mis parches (y también más personas usuarias de Fedora allegadas a mi), y estamos siendo capaces de firmar y cofirmar documentos perfectamente.

**Comment by Gamuci** [comment]
Los cambios ya han sido integrados en la rama principal del proyecto y estarán disponibles en AutoFirma 1.7. Muchas gracias.
