### ISSUE TITLE
[Win10] Problema al actualizar autofirma a última versión (1.7.2)

### ISSUE THREAD

**Issue by vrbouza** [ctt-gob-es/clienteafirma#283]
Hola.

A la hora de hacer un trámite se me exigió la última versión de autofirma (1.7.2), teniendo yo la 1.6.2. La descargué e instalé, pero al abrir autofirma, seguía abriendo la 1.6.2. Intenté borrar autofirma (desde configuración->programas->desinstalar->blabla) y reinstalar la nueva versión, pero a la hora de reinstalar dice que «esta versión ya está instalada en este equipo». 

Intenté hacer búsquedas globales de ficheros que pudieran quedar, limpié el registro (con CCCleaner), y reinicié y actualicé Win10 por si fuera la cosa, pero nada. ¿Hay alguna carpeta que deba borrar manualmente?

Gracias de antemano.

**Comment by Gamuci** [comment]
Hola, @vrbouza:

Supongo que ya habrás hecho lo clásico de ir a "Agregar o quitar programas" y comprobar que ahí no aparece la aplicación. También que habrás ido a "Archivos de programa -> AutoFirma" (o el que fuese tu directorio de instalación) y comprobado que la aplicación y su desinstalador no están ahí.

El propio AutoFirma no comprueba nada durante la instalación para saber si ya está instalado o no, pero si falló al desinstalar puede que Windows crea que está instalado cuando no lo está. Prueba a acceder al registro de Windows (_regedit.exe_) y acceder a la clave: _HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall_. Busca ahí si hay alguna entrada de AutoFirma. Puede aparecer directamente como "AutoFirma", pero mira también las entradas del principio con un código largo entre llaves. Revisa la cadena "UninstallString" y mira si en ese directorio realmente hay un desinstalador. Ejecútalo en ese caso. Si no lo hay, elimina toda la entrada (ten cuidado de no eliminar lo que no es). Después prueba a volver a instalar.

Consejos para instalar y desinstalar AutoFirma:
 - Como usuario usa siempre el instalador EXE. El MSI está pensado para que los administradores hagan los despliegues masivos.
 - Desinstala siempre a través del diálogo de Windows de "Agregar o quitar programas". Este ejecuta el instalador de AutoFirma y además se encarga de eliminar los registros que agrega Windows por su cuenta.

Un saludo.

**Comment by vrbouza** [comment]
Hola de nuevo @Gamuci .

Iba a escribir en esta incidencia hoy porque justo ayer lo arreglé, en parte haciendo lo que sugieres: no sé por qué, pero en el registro, en `HKEY_LOCAL_MACHINE\SOFTWARE`, aparecía una carpetina directamente como `AutoFirma`. Fue eliminarla (entera), y ya pude instalar correctamente la última versión (1.7.2, x86_64).

¡Gracias en todo caso! ¡Saludos!

**Comment by HuachaDev** [comment]
Si alguien mas presenta este tipo de incidente con el SO Windows y Autofirma , ingrese a regedit > HKEY_LOCAL_MACHINE > Software > Autofirma. Borre los ficheros y la carpeta. Finalmente instale la nueva versión y es todo
