### ISSUE TITLE
WARNING: All illegal access operations will be denied in a future release

### ISSUE THREAD

**Issue by Yakano** [ctt-gob-es/clienteafirma#295]
Hola

Estoy firmando ficheros PDF en Windows 10 y 11 con Autofirma 1.6.4, 1.6.5 y 1.7.2 desde la línea de comandos con...

AutoFirmaCommandLine.exe sign -i "FileIn.pdf" -o "FileOut.pdf" -store pkcs12:"Certificado.pfx" -password 12345 -filter subject.contains:B88888888 -config nlayer2Text="Firmado Digitalmente por $$SUBJECTCN$$ el Día $$SIGNDATE=dd/MM/yyyy HH:mm:ss$$ con Certificado Emitido por $$ISSUERCN$$"\nsignaturePositionOnPageLowerLeftX=35\nsignaturePositionOnPageLowerLeftY=845\nsignaturePositionOnPageUpperRightX=577\nsignaturePositionOnPageUpperRightY=815\nlayer2FontColor=red\nlayer2FontSize=8\nlayer2FontFamily=1\nlayer2FontStyle=2

Desde la versión 1.6.5 me saca los siguientes WARNINGs y no sé como eliminarlos...

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.jmimemagic.MagicParser (file:/C:/Program%20Files/AutoFirma/AutoFirma/AutoFirmaCommandLine.exe) to constructor com.sun.org.apache.xerces.internal.parsers.SAXParser()
WARNING: Please consider reporting this to the maintainers of net.sf.jmimemagic.MagicParser
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Por favor, alguien que lo haya resuelto y me pueda iluminar... 
(desesperado ya de buscar y no encontrar nada)

Gracias !!!

P.D. Lo que más me preocupa es donde dice "All illegal access operations will be denied in a future release" que parece que no es un mensaje de Autofirma, sino del "constructor com.sun.org.apache.xerces.internal.parsers.SAXParser()", avisando que algo no va bien y avisando después que se use "--illegal-access=warn", pero no he encontrado nada de eso en el [Manual del integrador del Cliente @firma v1.8](https://github.com/ctt-gob-es/clienteafirma-docs/blob/master/MCF_manual-integrador_ES.docx)

**Comment by Gamuci** [comment]
Buenas tardes,

El mensaje lo genera Java por el modo en el que opera la biblioteca JMulticard. He estado mirando el código de AutoFirma y, para tu caso concreto, hay una forma de evitarlo. La biblioteca JMulticard se utiliza para identificar el tipo de los datos que se están firmando (que en tu caso son PDF) y también para saber qué formato de firma utilizar cuando no se indica. Como no indicas en la llamada el formato de firma, AutoFirma identifica el tipo de los datos y selecciona uno acorde. En tu caso, PAdES.

Si agregas a la llamada el formato de firma (-format PAdES), dejará de mostrar esas línea.

Acabo de probar y con AutoFirma 1.8 no se muestra ese mensaje con la llamada que haces ahora.

Un saludo,
