### ISSUE TITLE
Falla la firma desde línea de comandos en Linux cuando el alias del certificado tiene espacios

### ISSUE THREAD

**Issue by dantefff** [ctt-gob-es/clienteafirma#296]
Cuando un álias de un certificado tiene espacios, por ejemplo:
```
$ AutoFirma listaliases
FULANITO DE TAL - 00000000H
```
Si se usa la línea de comandos para realizar firmas, la firma falla:
```
$ AutoFirma sign -alias "FULANITO DE TAL - 00000000H" -i ./entrada.pdf -o ./salida_firmada.pdf
No se reconoce el parametro DE
Sintaxis: AutoFirma sign [opciones...]
```

El error viene del script wrapper que ejecuta el jar de autofirma

**Comment by Gamuci** [comment]
Hola, @dantefff:

He estado probando y el problema parece venir del cómo pasa los parámetros el script "/usr/bin/AutoFirma". Prueba llamando directamente al JAR de AutoFirma:

java -jar /usr/lib/AutoFirma/AutoFirma.jar sign -alias "FULANITO DE TAL - 00000000H" -i ./entrada.pdf -o ./salida_firmada.pdf

Ten en cuenta que tendrás que tener en el PATH el ejecutable "java". Si no, tendrás que poner la ruta a este ejecutable. También tendrás que poner la ruta absoluta de los ficheros de entrada y salida.

**Comment by dantefff** [comment]
Gracias @Gamuci . Sí, lo vi en el momento, he hecho una pull request para arreglarlo:
https://github.com/ctt-gob-es/clienteafirma/pull/297
