### ISSUE TITLE
Al desinstalar la aplicación ya no deja volver a instalarla de nuevo

### ISSUE THREAD

**Issue by odarriba** [ctt-gob-es/clienteafirma#306]
En medio del caos de la versión 1.7.2 (muchas webs no han actualizado AutoScript y no funciona) he intentado desinstalar el cliente de AutoFirma e instalarlo de nuevo en la versión 1.7.0, y cual es mi sorpresa que al desinstalar el desinstalador se cierra sólo.

Una vez ocurre esto, ya no deja instalar de nuevo, porque ha dejado algo en el sistema y:
- La versión 1.7.0 dice que ya hay una versión más nueva instalada
- La versión 1.7.2 dice que esa versión ya está instalada

He buscado en el registro y en el sistema de ficheros y borrado todo lo relacionado con AutoFirma que he podido encontrar, sin suerte.

¿A alguien más le ha pasado?
¿Se puede solucionar sin reinstalar todo el ordenador?

**Comment by acuartango** [comment]
Hola,

Autofirma se cierra automáticamente si tienes arrancadas algunas aplicaciones (Por ejemplo el Enterprise Single Sign On de Oracle), con lo que si se cierra ese software (o se desinstala) y se intenta de nuevo, funciona. Lo comento por si tienes programas arrancados que puedan interferir con autofirma (prueba a cerrar todos los que se quedan residentes en la barra de tareas abajo a la derecha)

Si este no es el problema deberías:

1.- Eliminar manualmente la carpeta de autofirma de C:\Archivos de programa\autofirma
2.- Eliminar la carpeta temporal de ".autofirma" dentro de tu perfil de usuario
2.- Abre regedit con permisos de administrador y elimina todas las entradas donde aparezca la palabra "autofirma"
3.- Reinstala autofirma y reinicia

Creo que con esto te debería funcionar sin problemas. 

mucha suerte

**Comment by odarriba** [comment]
Al final estuve bicheando en el script del NSIS que es el instalador, y vi que había que eliminarlo del registro en HKLM/SOFTWARE/AutoFirma.

Eliminada esa carpeta del registro y pude reinstalar sin problema.

Gracias!
