### ISSUE TITLE
Trojan.OSX.Nukesped

### ISSUE THREAD

**Issue by lorenzoFabbri** [ctt-gob-es/clienteafirma#384]
Subí la aplicación AutoFirma para MacOS a VirusTotal porque no se reconocía la firma de la aplicación. En VirusTotal, el servicio Ikarus detectó "Trojan.OSX.Nukesped". es posible?

<img width="1080" alt="image" src="https://github.com/ctt-gob-es/clienteafirma/assets/22343884/547f3fdf-70ae-4a99-9326-e78ad68430c0">

**Comment by Gamuci** [comment]
Acabo de probar y me sale limpio, tanto el instalador como los ejecutables. ¿Qué estás mandando exactamente y de qué versión?

**Comment by lorenzoFabbri** [comment]
> Acabo de probar y me sale limpio, tanto el instalador como los ejecutables. ¿Qué estás mandando exactamente y de qué versión?

https://www.virustotal.com/gui/file/f359e182185889a77e811369d81d7e0b80825eeb32b668b0d73fdab768db62bc/detection

**Comment by gonzaleztroyano** [comment]
@lorenzoFabbri, he probado a _[reanalizar](https://www.virustotal.com/gui/file/f359e182185889a77e811369d81d7e0b80825eeb32b668b0d73fdab768db62bc/detection)_ el archivo desde VirusTotal y ahora no detecta ninguna amenaza:
![image](https://github.com/ctt-gob-es/clienteafirma/assets/44492590/127a9f49-48f4-40ec-bbb4-012cca7e0a2d)

Quizá se trate simplemente de un falso positivo.

Viendo el _hash_ del archivo subido a VirusTotal, parece que utilizaste la opción de descargar el repositorio desde Github, ¿puede ser?

**Comment by lorenzoFabbri** [comment]
> @lorenzoFabbri, he probado a _[reanalizar](https://www.virustotal.com/gui/file/f359e182185889a77e811369d81d7e0b80825eeb32b668b0d73fdab768db62bc/detection)_ el archivo desde VirusTotal y ahora no detecta ninguna amenaza: ![image](https://private-user-images.githubusercontent.com/44492590/318832562-127a9f49-48f4-40ec-bbb4-012cca7e0a2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzE3MTYsIm5iZiI6MTcxMjA3MTQxNiwicGF0aCI6Ii80NDQ5MjU5MC8zMTg4MzI1NjItMTI3YTlmNDktNDhmNC00MGVjLWJiYjQtMDEyY2NhN2UwYTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE1MjMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMjI2ZWYyMzIxYjEzOGMzYjUyZDAxMjhhN2VkYmRmYWMxYmJkNjIwODJhMjVkZmViOTk2MWIzNDcwZjRkMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y633zvBMcker-MjhKh33SjNwpVRZqa5IIdVVvR3HGN0)
> 
> Quizá se trate simplemente de un falso positivo.
> 
> Viendo el _hash_ del archivo subido a VirusTotal, parece que utilizaste la opción de descargar el repositorio desde Github, ¿puede ser?

Probé tanto con el repositorio de Git como cargando la aplicación que instalé en mi computadora portátil. Lo intenté de nuevo ahora y también obtengo indicadores 0/50.

**Comment by Gamuci** [comment]
Doy por cerrado el caso. Muchas gracias @lorenzoFabbri y @gonzaleztroyano.
