### ISSUE TITLE
Ausencia de dependencias construyendo según el README

### ISSUE THREAD

**Issue by Aestu** [ctt-gob-es/clienteafirma#50]
Simplemente clono el repositorio con 

`git clone github:ctt-gob-es/clienteafirma`

Después siguiendo las instrucciones del README ejecuto:

`mvn clean install`

pero faltan dependencias:

`[ERROR] Failed to execute goal on project afirma-core: Could not resolve dependencies for project es.gob.afirma:afirma-core:jar:1.6.4-SNAPSHOT: Could not find artifact es.gob.afirma.lib:afirma-lib-jmimemagic:jar:0.0.5-SNAPSHOT -> [Help 1]
`

**Comment by Gamuci** [comment]
El Cliente @firma está ligado a JMulticard y versiones modificadas de algunas otras bibliotecas. Las versiones SNAPSHOT del Cliente pueden dependender de versiones SNAPSHOT de estas bibliotecas.

Si quieres obtener la versión estable de los artefactos del Cliente @firma, utiliza las versiones etiquetadas.

Si quieres empaquetar la última SNAPSHOT, quizás tengas que empaquetar también los artefactos que se encuentran en:
 - https://github.com/ctt-gob-es/clienteafirma-external
 - https://github.com/ctt-gob-es/jmulticard

**Comment by gstvrmrlpz** [comment]
Perdón por la mi torpeza, pero, ¿eso cómo se hace?

**Comment by Gamuci** [comment]
Descargate los fuentes de esos otros dos proyectos ("clienteafirma-external" y "jmulticard"), hazles el "mvn clean install" y después vuelve a intentarlo con el proyecto "clienteafirma". Asegurate de tener descargada la última versión de todo.

**Comment by gstvrmrlpz** [comment]
con clienteafirma-externa funciona bien, pero con jmulticard escupe el siguiente error:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] jmulticard-android 1.5 ............................. FAILURE [  0.543 s]
[INFO] jmulticard-jsr268 .................................. SKIPPED
[INFO] jmulticard-ui ...................................... SKIPPED
[INFO] jmulticard-jse 1.5 ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.947 s
[INFO] Finished at: 2019-02-21T11:53:30+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.3.0:generate-sources (default-generate-sources) on project jmulticard-android: No Android SDK path could be found. You may configure it in the plugin configuration section in the pom file using <sdk><path>...</path></sdk> or <properties><android.sdk.path>...</android.sdk.path></properties> or on command-line using -Dandroid.sdk.path=... or by setting environment variable ANDROID_HOME -> [Help 1]

**Comment by Gamuci** [comment]
Hola @gstvrmrlpz ,

Perdón. Recientemente se agregó a la construcción por defecto de JMulticard su biblioteca para funcionar en Android y esta requiere el SDK de Android. Ya lo quité del por defecto y lo agregué a un perfil aparte.

Un saludo.

**Comment by Gamuci** [comment]
AutoFirma 1.6.5 y sus dependencias ya se han publicado en el repositorio central de Maven. Cuando se realicen nuevos cambios en AutoFirma se actualizará la versión a SNAPSHOT. La versión de sus dependencias se mantendrán hasta que también se realicen cambios en ellas. A partir de entonces, también habrá que descargarse la última versión de todo para poder obtener la última SNAPSHOT.

**Comment by josalesmj** [comment]
I build jmulticard with: 
`sudo mvn clean install -DskipTests`
After I build clienteafirma-external with:
`sudo mvn clean install -DskipTests`
And tried to build clienteafirma with:
`sudo mvn clean install -Denv=install`

But I got the following error:

[ERROR] Failed to execute goal on project afirma-ui-miniapplet: Could not resolve dependencies for project es.gob.afirma:afirma-ui-miniapplet:jar:1.7: The following artifacts could not be resolved: es.gob.afirma:afirma-core-keystores:jar:1.7, es.gob.afirma:afirma-keystores-mozilla:jar:1.7, es.gob.afirma:afirma-keystores-filters:jar:1.7, es.gob.afirma:afirma-crypto-cades:jar:1.7, es.gob.afirma:afirma-crypto-cades-multi:jar:1.7, es.gob.afirma:afirma-crypto-core-pkcs7:jar:1.7, es.gob.afirma:afirma-crypto-core-pkcs7-tsp:jar:1.7, es.gob.afirma:afirma-crypto-cms:jar:1.7, es.gob.afirma:afirma-crypto-xades:jar:1.7, es.gob.afirma:afirma-crypto-core-xml:jar:1.7, es.gob.afirma:afirma-crypto-xmlsignature:jar:1.7, es.gob.afirma:afirma-crypto-pdf:jar:1.7, es.gob.afirma:afirma-crypto-odf:jar:1.7, es.gob.afirma:afirma-crypto-ooxml:jar:1.7, es.gob.afirma:afirma-ui-core-jse:jar:1.7, es.gob.afirma:afirma-ui-core-jse-keystores:jar:1.7, es.gob.afirma:afirma-crypto-cadestri-client:jar:1.7, es.gob.afirma:afirma-crypto-padestri-client:jar:1.7, es.gob.afirma:afirma-crypto-xadestri-client:jar:1.7, es.gob.afirma:afirma-crypto-batch-client:jar:1.7, es.gob.afirma.jmulticard:jmulticard-jse:jar:1.6: Failure to find es.gob.afirma:afirma-core-keystores:jar:1.7 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

Could you help me, please?
