### ISSUE TITLE
Instalacion de Autofirma para RPM 

### ISSUE THREAD

**Issue by hhlp** [ctt-gob-es/clienteafirma#56]
Sorprendentemente la aplicacion autofirma esta solo para deb. una aplicación nececesaria para realizar tramietes con el gobierno.

Estoy en esto de los certificados digitales, DNI electrónico y todo ese asunto digital para tener acceso a los tramites digitales en las administraciones publicas... ya que hay una orden ministerial que desde el día 1 de octubre los trabajadores autonomos deben realizar sus tramites por via electronica.

mi sugerencia es la siguiente :

la Aplicación Autofirma nada más esta disponible para los siguientes Sistemas Operativos :

1.- Windows tanto 32 como 64
2.- Debian y sus derivados (Ubuntu, guadalinex, etc)

Mi pregunta es la siguiente :

Que pasa con las distribuciones basadas en Red Hat que manejan paquetes rpm como :

1.- Fedora

Udes. podrían realizar el paquete AutoFirma en rpm para estas distribuciones (colgarlo en el portal) y ser un poco alma caritativas con nosotros, usuarios de estas distribuciones, realmente es un HARA-KIRI realizar esto con ALIEN y convertirlo o hacer un RPM por nuestra propia cuenta, ya que no funciona tal cual, y se generan muchos errores...

aquí le pongo un ejemplo de lo que les estoy explicando : 

[https://linuxcasual.wordpress.com/2017/08/19/alien-y-el-dni-electronico-en-fedora-26/](url)

yo estoy con oracle java 8/9/10/11 y fedora 29 ... Firefox 62 en 64 bits...

Muchísimas Gracias por su atención de antemano...

Atentamente,

**Comment by franpsmontero** [comment]
Me sumo totalmente a la petición de mejorar la disponibilidad de AutoFirma para rpm

**Comment by amunozf** [comment]
Y reza para que te funcione porque Autofirma 1.6.2 no es compatible con las últimas versiones de Firefox en Linux.

**Comment by hhlp** [comment]
@alfem 

y se pueder saber como lo instalastes...

**Comment by victorjss** [comment]
Me repito (perdón), pero no debemos bajar a Java 8 todo el sistema:

https://github.com/ctt-gob-es/clienteafirma/issues/16#issuecomment-456057442

**Comment by ssaavedra** [comment]
Aún así, como Autofirma tiene atornilladas las rutas de las dependencias (véase [MozillaKeyStoreUtilitiesUnix.java#L26-L42](https://github.com/ctt-gob-es/clienteafirma/blob/master/afirma-keystores-mozilla/src/main/java/es/gob/afirma/keystores/mozilla/MozillaKeyStoreUtilitiesUnix.java#L26-L42), y Fedora utiliza la convención de mantener /usr/lib para libs de 32 bits y utilizar /usr/lib64 para libs de 64 bits, pues todo se rompe, como he dicho el año pasado ya en [otro comentario](https://github.com/ctt-gob-es/clienteafirma/issues/16#issuecomment-376721896). Así que no es solamente cuestión de reempaquetar con alien.

**Si estás utilizando una versión de Fedora de 64 bits, los workarounds actuales son**:

- O bien hacer symlinks de todas las dependencias de 64 bits desde /usr/lib64/libwhatever.so a /usr/lib/libwhatever.so (y nunca necesitar la versión de 32 bits en paquetes que sigan las Fedora Packaging Guidelines)
- O bien parchear AutoFirma modificando el fichero MozillaKeyStoreUtilitiesUnix.java para que tenga en cuenta /usr/lib64 lo primero, y compilarlo nosotros.
- O bien parchear AutoFirma modificando el fichero MozillaKeyStoreUtilitiesUnix y refactorizando el código necesario para que se obtengan rutas en base a algo más elaborado (e.g., probar en este orden `"/usr/lib" + Platform.getJavaArch()`, `"/usr/lib"` y luego todas las contingencias necesarias, si continuasen siendo necesarias), y subirlo aquí como PR :-)

**Comment by Gamuci** [comment]
La nueva versión 1.6.5 de AutoFirma, que se publicará próximamente, incluirá una distribución RPM. Esta versión será compatible con OpenJDK 11.

Aviso a los usuarios de Fedora: la OpenJDK que incluye es una versión "headless" y no incluye las bibliotecas para mostrar diálogos gráficos. Tendrán que instalarse una OpenJDK estándar para poder ejecutar AutoFirma (aunque sí que se podrá instalar con la que viene por defecto).

Gracias a todos por los aportes.

**Comment by pr-apes** [comment]
Buscando el archivo RPM, que está habilitado con 8af9b895d8dbe8f94676304fa89ca6292cd0cfe7, sólo consigo encontrar https://estaticos.redsara.es/comunes/autofirma/currentversion/AutoFirma_Linux.zip.

Por si alguien lo sabe, tengo dos preguntas:

* ¿Dónde puedo encontrar `instalador_linux_rpm.tar.gz`?

* ¿Existen (o hay algún plan de publicar) versiones de 64bit para _macOS_ o _Linux_?

Muchas gracias.

**Comment by alfem** [comment]
Aquí tienes el último (la 1.6.5). Es un .zip que dentro lleva tanto el .rpm como el .deb
Que yo sepa son para 64 bits.

https://firmaelectronica.gob.es/Home/Descargas.html

**Comment by pr-apes** [comment]
@alfem, muchas gracias por la información. Daba por hecho que el archivo comprimido sólo tendría la instalación para sistemas _Debian_.
