### ISSUE TITLE
AutoFirma no funciona con openjdk11 (Debian buster)

### ISSUE THREAD

**Issue by LuisLlana** [ctt-gob-es/clienteafirma#65]
El programa de autofirma no funciona correctamente con la versión de java por defectro de Debian Buster (openjdk-11). Supongo que pasará lo mismo con las versiones recientes de Ubuntu. Para que funcione es necesario instalar la verisión 8 de openjdk.

**Comment by Gamuci** [comment]
Hola LuisLlana,

Gracias por el aviso. Ya estamos haciendo cambios en AutoFirma para ser compatibles con OpenJDK-11. Sin embargo, no se hacen pruebas con todas las distribuciones de Linux, así que nos viene bien que nos aviséis cuando detectéis problemas concretos. ¿Qué es lo que no te funciona con Debian Buster?, ¿No arranca la aplicación?, ¿No se lanza al ejecutar la operación de firma desde el navegador o no se comunica con él?, ¿Falla el acceso al almacén?, ¿Falla alguna operación o formato de firma concreto?...

Un saludo.

**Comment by Gamuci** [comment]
Ya se ha publicado AutoFirma 1.6.5, compatible con OpenJDK 11.
