### ISSUE TITLE
Autofirma no toma en consideración las excepciones de proxy del navegador

### ISSUE THREAD

**Issue by jmarsj** [ctt-gob-es/clienteafirma#66]
Buenos días
Autofirma no toma en consideración las excepciones de proxy

Cuando una organización dispone de proxy explicito y tiene configuradas excepciones en el navegador. Autofirma no las toma en consideración.

Esto es importante por varios motivos:

1.	Cuando quieres hacer una firma a una web interna lo normal es no utilizar proxy.

2.	A la hora de realizar granjas web para firma de documentos. El balanceo de la petición siempre se envía desde el proxy y no puedes realizar persistencia de servidor por IP al ser siempre el servidor proxy quien realiza la conexión

3.	Java en su configuración de red tiene implementadas todas las opciones de proxy necesarias en su panel de control.

Un saludo

**Comment by alfem** [comment]
Como Autofirma es una aplicación 'standalone', quizás obedezca a la configuración de proxy del sistema, en lugar de la del navegador.

**Comment by jmarsj** [comment]
Podría ser. Pero tampoco hace caso a las excepciones del sistema.

Por otro lado. Las configuraciones las realiza en la zona de registro del usuario 

Entiendo que si defino proxy en autiofirma debería también poder incluir las excepciones.

He conseguido un workaround modificando el net.properties del java de autiofirma y pasando de la configuración de proxy en la aplicación. Es un poco chapu pero de momento me sirve.

**Comment by Gamuci** [comment]
Esta planificado para un futuro próximo el seguir trabajando sobre la configuración de proxy de AutoFirma. Se va a intentar que se pueda utilizar la configuración de proxy del sistema tal cual (incluyendo excepciones), y es muy probable que se permita configurar en AutoFirma una lista de excepciones propia.

**Comment by imorales** [comment]
@Gamuci  ¿han podido avanzar sobre esta mejora?

Muchas gracias.

**Comment by Gamuci** [comment]
Hola @imorales, 

Los cambios que finalmente se han aplicado son:

- Se han corregido algunos errores en la configuración del proxy.
- Se ha modificado la interfaz de configuración para clarificar el comportamiento esperado de las distintas opciones.
- Se ha incluido una lista de excepciones propia para cuando se establece la configuración manual del proxy de AutoFirma.

Dejo el issue ya cerrado. Saludos.

**Comment by imorales** [comment]
Hola @Gamuci,

muchas gracias por informar, solo una duda. Tengo instalada la versión 1.6.5 y no encuentro la opción donde indica que se incluyen la lista de excepciones propia.

Muchas gracias.

**Comment by Gamuci** [comment]
El cambio ya está en el código, pero aún no se ha publicado ninguna versión que lo contenga. Podrás verlo en AutoFirma 1.7, que se publicará próximamente. No sé darte una fecha aproximada de publicación, pero espero que no tarde.
