### ISSUE TITLE
Autofirma no detecta con qué programa debe abrir los ficheros contenidos en una firma .csig

### ISSUE THREAD

**Issue by JoSe086** [ctt-gob-es/clienteafirma#69]
Estoy firmando un archivo office antiguo (.xls) con el programa de Autofirma, y éste me genera un archivo .csig que contiene dentro el fichero original.

Cuando abro el archivo .csig con Autofirma y hago click en la opción "Ver datos firmados", el programa no detecta correctamente la extensión del archivo y me lo intenta abrir con el word. Por curiosidad he probado a hacer lo mismo con un archivo powerpoint (.ppt) y también lo intenta abrir con word.

Con otros archivos (como .txt) hago la misma prueba y al intentar ver los datos firmados tampoco detecta la extensión (por lógica, debería abrirlo con el bloc de notas) y en lugar de eso, me dice que guarde el fichero en disco.

Esto sólo pasa con ciertas extensiones, ya que por ejemplo las imágenes las abre correctamente.

**Comment by Contasimple** [comment]
Hola Gamuci,

muchas gracias por tu explicación sobre los ficheros TXT y por la rapidez corrigiendo el problema.

Un saludo.

**Comment by JoSe086** [comment]
Hola Gamuci,

muchas gracias por tu explicación de los ficheros TXT y por la rapidez resolviendo el problema.

Un saludo.

**Comment by enriverd** [comment]
Hola Gamuci, 

Gracias por corregir dicha funcionalidad, a nosotros también nos resuelves un problema. No obstante, respecto a los TXT, entiendo que está muy bien analizar el contenido del fichero para confirmar si realmente contiene el tipo de dato definido por su extensión, pero en el caso de que dicho análisis no pueda adivinar el contenido, ¿no creéis que fiarse de la extensión es una solución suficientemente buena? Es más, si nos ceñimos a probabilidades es más probable que aciertes si abres todos los TXT directamente con un editor de texto que si, or el contrario, solo lo haces cuando el análisis de contenido te indica que contiene texto. Con esto quiero decir que creo que vuestro usuarios agradecerían, entre ellos nosotros, que cuando no hayáis podido adivinar el contenido os fiéis de la extensión.
