### ISSUE TITLE
error: el almacén no contiene ningún certificado que se pueda usar para firmar

### ISSUE THREAD

**Issue by icf20** [ctt-gob-es/clienteafirma#70]
![image](https://user-images.githubusercontent.com/17784575/48974455-82fad680-f05a-11e8-9d4f-6e27df2cde52.png)

sin embargo el certificado va muy bien con firefox 63.0.3

ubuntu 18.10

**Comment by amunozf** [comment]
Confirmo que este problema existe también en la distribución KDE Neon, basada en Ubuntu 18.04. Los certificados funcionan bien con el navegador Firefox 63.0.3.

Por lo que tengo entendido, el problema viene de que las versiones nuevas de Firefox almacenan los certificados en otro archivo de base de datos diferente que Autofirma y otros programas (p.ej.: Libreoffice) no reconocen todavía.

**Comment by calvaris** [comment]
Yo tuve este problema y se solucionó asegurándome que la versión por defecto de Java que se ejecutaba era la 1.8. En mi caso la disto es debian y lo hice con los alternatives.

**Comment by Gamuci** [comment]
Hola @icf20,

Es como dice @amunozf, los almacenes de Firefox y del sistema son distintos. Puede que tengas tu certificado en el almacén de Firefox y no en el otro.

Si puedes, haz una prueba y pon aquí la traza de ejecución para ver cual es el error (debe guardarse en tu directorio de usuario -> .afirma -> AUTOFIRMA.afirma.log.xml). Con eso deberíamos ver el problema.

Un saludo.

**Comment by icf20** [comment]
no te puedo poner el log ya no tengo ubuntu en arch ya no tengo ese problema

**Comment by tonikasch** [comment]
El bug sigue presente en Ubuntu 18.04 con Firefox 65.0.1 y Java OpenJDK-8
Entiendo que si instalo Firefox ESR es una manera de parchear esto.
Pero no es una solución.
El problema no está solucionado ni mucho menos.

**Comment by AMArostegui** [comment]
El problema sigue apareciendo cuando trato de firmar un documento PDF desde la web de la Junta de Andalucía. En concreto, con el modelo 806.

En mi caso, bajo Windows 10 (x64), Firefox 69.0, AutoFirma 1.6.0.JAv01

Según he visto en los comentarios, instalando por defecto Java 8 a algunas personas se les soluciona el problema. Además, en otra incidencia relacionada se hace hincapié en que debe ser Oracle Java, no siendo válido OpenJDK.

En mi caso, lo anterior no me ha funcionado, teniendo como versión por defecto Oracle Java 8, versión 1.8.0_181.

Son dos los problemas que se presentan:

1) Autofirma no es capaz de detectar o importar el certificado que uso habitualmente en Firefox
2) Firefox no es capaz de invocar correctamente la aplicación local Autofirma

Para resolver el problema (1) he importando el certificado al almacén de Windows, de la siguiente manera:

En Firefox, exportar el certificado Herramientas => Opciones => Privacidad y Seguridad => Certificados => Ver certificados => Hacer copia, como archivo PKCS12 (*.p12)

En Windows, en Panel de Control => Opciones de Internet => Contenido => Certificados => Importar, pues eso, el archivito anterior

Ahora Autofirma ya es capaz de firmar un PDF con tu certificado, pero a la hora de adjuntar el documento y firmarlo desde Firefox, el navegador invoca correctamente al programa local Autofirma, ya que aparece una ventana del sistema pidiendo permisos, pero por algún motivo el programa no arranca y por tanto no somos capaces de firmar el archivo.

En este punto no me ha quedado más remedio que utilizar Internet Explorer 11, volver a iniciar el proceso, en cuyo caso Autofirma se invoca correctamente y es capaz de firmar el archivo.

**Comment by icf20** [comment]
> Internet Explorer 11

eso aun tiene soporte por parte de microsoft?

**Comment by AMArostegui** [comment]
> 
> 
> > Internet Explorer 11
> 
> eso aun tiene soporte por parte de microsoft?

Creo que no, pero para esto en concreto, no me ha quedado más remedio que usarlo.

**Comment by CarlvO** [comment]
Alguien sabría cómo solucionarlo en Linux?

Y, de paso, cuando van a modernizar eso de los applets de java y herramientas cutres para identificarte en el portal de la Junta de Andalucía? Con el IRPF nunca tengo problemas, pero cualquier trámite online con la junta es un sinfin de horrores informáticos.

**Comment by cmorenoruiz** [comment]
Mismo error en Ubuntu 20.04.1 LTS.
Firefox y Chrome reconocen el certificado, pero SeaHorse 3.36 no permite importar el certificado. El botón "Importar" aparece inhabilitado y el mensaje que muestra es "No se puede importar porque no hay importadores compatibles".
Así que Autofirma es incapaz de obtener el certificado de SeaHorse, porque no está en él y tengo que importarlo cada vez que quiero firmar.

**Comment by icf20** [comment]
dios es 2020 y esto siguen sin ser resuelto

+1 razon para dejar de pagar impuestos

**Comment by alborrajo** [comment]
2021 y mas de lo mismo, sigue dando el mismo problema en JDK 8 de Oracle, OpenJDK 8, OpenJDK 11 y OpenJDK 16

**Comment by jjgomera** [comment]
El error es como comenta calvaris, autofirma exige java8 pero no es la versión que se ejecuta por defecto, 

`update-alternatives --config java`

 y elegid la versión 8

**Comment by JorgeDuenasLerin** [comment]
oh!!! noviembre de 2023. Es una vergüenza la precariedad tecnológica que tienen todas las administraciones.

Esperemos que la IA deje obsoletos a todos los técnicos mediocres.

(Soy funcionario docente en la comunidad de Madrid y las plataformas tecnológicas son malas, poco intuitivas, dificultan las tareas, funcionan de forma intermitente...)

**Comment by Dev4lexG** [comment]
Normal que vaya mal las cosas. Parece que lo quieren así para dificultarnos y que no podamos hacer las cosas = Más para ellos, menos para nosotros.
