### ISSUE TITLE
No aparece visible la ventana para introducir la contraseña del certificado

### ISSUE THREAD

**Issue by dfrigolet** [ctt-gob-es/clienteafirma#72]
Al intentar seleccionar un certificado que no está instalado en la máquina no aparece visible la ventana para introducir la contraseña. 

Pasos para reproducir:

- Abrir Autofirma
- Seleccionar fichero a firmar
- Clic en el icono "Abrir almacén de claves externo"
- Seleccionar certificado

Se queda bloqueado y la ventana para introducir contraseña no aparece visible. Realmente si está (se adjunta captura) y si escribes la contraseña y pulsas Intro, se carga correctamente el certificado y permite firmar.

Autofirma 1.6.3
Windows 10
Pasa firmando en local en la máquina y también invocando  Autofirma desde la web

![perla_autofirma](https://user-images.githubusercontent.com/44998000/50268448-babf2900-0422-11e9-80d3-2ace358bc48b.png)

**Comment by Gamuci** [comment]
Esto ya se ha corregido. También se ha corregido que al pulsar en el botón actualizar cuando se visualizaba un almacén externo se dejaban de ver los certificados y se ha hecho que al no encontrar certificados válidos en el almacén se muestre el diálogo de selección sin certificados. Así se da la posibilidad de seleccionar un almacén externo o utilizar una tarjeta inteligente que no se tuviese insertada en al principio.
