### ISSUE TITLE
Instalación en Windows no termina (Firefox con contraseña maestra)

### ISSUE THREAD

**Issue by fenevol** [ctt-gob-es/clienteafirma#73]
Versión de AutoFirma: 1.6.3
Versión de Ms. Windows: Windows 10
Versión de Mozilla Firefox: 64.0

El instalador se queda con el mensaje:
```
Extrayendo : "C:\Program Files\AutoFirma\AutoFirma\AutoFirmaConfigurador.exe" /passive
```
y no termina de instalar la aplicación.

El problema radica en que al tener Firefox una contraseña maestra para el inicio de sesión y contraseñas, como el instalador no solicita esta contraseña, no puede acceder a la base de datos con los certificados de Firefox.

**Solución temporal**: si se elimina la contraseña maestra en firefox, AutoFirma se instala correctamente. Una vez instalada la aplicación, se puede habilitar la contraseña maestra ya que AutoFirma muestra un cuadro para introducir dicha contraseña cuando es necesario.

**Comment by Gamuci** [comment]
Problema solventado. Al instalar el usuario la aplicación, si se detecta que el almacén tiene una contraseña maestra, se le pedirá para completar el proceso.

Pronto se debería publicar una versión 1.6.5 de AutoFirma con este y otros muchos cambios.
