### ISSUE TITLE
Avisar sobre versión de Java no soportada

### ISSUE THREAD

**Issue by calvaris** [ctt-gob-es/clienteafirma#75]
Como se hace referencia en otras issues #65 #70, parece que versiones de Java más modernas no están soportadas y se dan errores crípticos como que los certificados no se encuentran. Quizás AutoFirma debería avisar en el arranque de que la versión de Java no está soportada y que se pueden dar errores.

**Comment by Gamuci** [comment]
Se está actualizando AutoFirma para ser compatible con OpenJDK 11. En cualquier caso, hemos seguido tu consejo y ahora, cuando se ejecute AutoFirma en modo escritorio, se mostrará un mensaje de advertencia si se ejecuta con una versión de Java no compatible.

No habrá advertencia cuando se llame AutoFirma desde un navegador, por no interrumpir el proceso de firma; ni desde consola, por no cambiar el mensaje esperado por el usuario.

**Comment by eboukamza** [comment]
He tenido el problema que se menciona en #70 y se arregló utilizando java8 en vez de java 10. 
Uso Ubunto 20.04 (bionic)
Creo que se debería de avisar de esto en el manual de instalación.
El mensaje de advertencia no se mostró en ningún momento y fue bastante frustrante.
