### ISSUE TITLE
Sellos de tiempo TSA

### ISSUE THREAD

**Issue by vk496** [ctt-gob-es/clienteafirma#77]
Buenas,

Se pueden realizar firmas con sellos de tiempo? Sería una característica muy útil a la hora de firmar ciertos documentos.

Salu2

**Comment by Gamuci** [comment]
Hola @vk496 ,

En general, el sello de tiempo no es algo que agregue el usuario que realiza una firma, sino la entidad que la recibe. La proyección de AutoFirma siempre ha sido el servir para realizar las operaciones de usuario, y se deja a un lado toda aquella operación que depende de un servicio remoto, como son los sellos de tiempo.

AutoFirma dispone, aunque no tiene soporte oficial, de las funciones para agregar sellos de tiempo a las firmas CAdES y PAdES, aunque estas sólo pueden usarse desde una operación realizada a través del JavaScript de despliegue del Cliente @firma. No se pueden generar desde la interfaz de escritorio.

Un saludo.
