### ISSUE TITLE
XolidoSign

### ISSUE THREAD

**Issue by acaeronte** [ctt-gob-es/clienteafirma#79]
Buenas,
Cuando firmo un pdf con el software XolidoSign y después quiero volver a firmar con otra firma el pdf, con el servicio de @firma me produce un error.
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <soapenv:Fault>
         <faultcode>soapenv:Server</faultcode>
         <faultstring>CORBA MARSHAL 0x4942f896 No; nested exception is: 
	org.omg.CORBA.MARSHAL: Unable to read value from underlying bridge : Unable to read value from underlying bridge</faultstring>
         <detail/>
      </soapenv:Fault>
   </soapenv:Body>
</soapenv:Envelope>

**Comment by Gamuci** [comment]
Esta incidencia no está relacionada con el Cliente @firma. Por favor, redirígela al servicio de soporte que corresponda de la solución @firma que utilices.
