### ISSUE TITLE
La compilación de 1.6.5 falla en Fedora

### ISSUE THREAD

**Issue by raimundojimenez** [ctt-gob-es/clienteafirma#80]
La compilación de 1.6.5 falla en Fedora
La compilación busca librerías más actualizadas de las que están subidas al repositorio central  https://search.maven.org/search?q=es.gob.afirma que no se actualiza desde marzo de 2018

Downloading from central: https://repo.maven.apache.org/maven2/es/gob/afirma/lib/afirma-lib-jmimemagic/0.0.5/afirma-lib-jmimemagic-0.0.5.pom
[WARNING] The POM for es.gob.afirma.lib:afirma-lib-jmimemagic:jar:0.0.5 is missing, no dependency information available
...
[INFO] afirma-client 1.6.5 ................................ SUCCESS [  3.219 s]
[INFO] afirma-core ........................................ FAILURE [  0.902 s]
...
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.364 s
[INFO] Finished at: 2019-03-29T19:56:38+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project afirma-core: Could not resolve dependencies for project es.gob.afirma:afirma-core:jar:1.6.5: Could not find artifact es.gob.afirma.lib:afirma-lib-jmimemagic:jar:0.0.5 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :afirma-core

**Comment by Gamuci** [comment]
El Cliente @firma siempre utiliza la última versión de los módulos de:

https://github.com/ctt-gob-es/clienteafirma-external.git
https://github.com/ctt-gob-es/jmulticard.git

Puedes descargar la última versión del código de estos módulos y compilarlos, aunque esperamos que en breve se suba una nueva versión al repositorio central de Maven con la versión estable de todos los artefactos.

**Comment by Gamuci** [comment]
La versión 1.6.5 se ya está disponible desde el repositorio central de Maven.
