### ISSUE TITLE
Error cargando almacén de certificados en Firefox cuando se tienen dos perfiles diferentes

### ISSUE THREAD

**Issue by rmunozrodriguez** [ctt-gob-es/clienteafirma#86]
Pasos para reproducir el problema:
1. Inicia Firefox (perfil predeterminado, lo llamaremos "Perfil 1") e importa un certificado digital que llamaremos "Certificado 1".
2. Probamos Autofirma por ejemplo en https://sede.carm.es/cryptoApplet/ayuda/probarautofirma.html y vemos que se carga el almacén de certificados del "Perfil 1" y nos aparece el "Certificado 1".
3. Creamos otro perfil que llamaremos "Perfil 2" e importamos un "Certificado 2".
4. Probamos nuevamente Autofirma en este segundo perfil y vemos que aparece el "Certificado 2".
5. Cargamos nuevamente el "Perfil 1" y probamos Autofirma otra vez, mostrándose en ésta ocasión únicamente el "Certificado 2" que tenemos en el almacén de certificados del "Perfil 2". No podemos usar por tanto el "Certificado 1".

La conclusión a la que he podido llegar, es que en el momento en que tenemos dos perfiles en Firefox, Autofirma siempre carga el almacén de certificados del segundo perfil que hemos creado, independientemente de que estemos trabajando en uno o en otro.

Probado en: Windows 10, Firefox 67 y Autofirma 1.6.5. Todo en versión 64 bits.

**Comment by alfem** [comment]
En teoría Autofirma usa el perfil que Firefox haya arrancado. Si no hay un Firefox arrancado, usa el que esté marcado por defecto (en el profiles.ini de Firefox), y si no hay ninguno por defecto, usa el primero que encuentra.

También se supone que hay unas variables de entorno para forzar el perfil que debe utilizar, pero no consigo que me funcione:

_private static final String AFIRMA_NSS_HOME_ENV = "AFIRMA_NSS_HOME_ENV"; //$NON-NLS-1$
private static final String AFIRMA_NSS_PROFILES_INI = "AFIRMA_NSS_PROFILES_INI"; //$NON-NLS-1$_

**Comment by rmunozrodriguez** [comment]
Por lo que yo he podido comprobar en varios equipos distintos, da igual el perfil que esté marcado por defecto en Firefox o el que tengas abierto en ese momento, ya que siempre cargará el almacén de certificados del segundo perfil que se creó.

**Comment by rmunozrodriguez** [comment]
Compruebo además que este bug es más notorio en una instalación limpia de Firefox 67, ya que a partir de ésta versión recientemente publicada, por defecto se crean dos perfiles (https://blog.nightly.mozilla.org/2019/01/14/moving-to-a-profile-per-install-architecture/). El primero "default-release" (perfil por defecto) y el segundo "default". Así, un usuario común que desconozca éste doble perfil y que instale sus certificados en Firefox con normalidad, comprobará que Autofirma le dice que "no hay certificados" ya que está buscando en "default". Es necesario eliminar ese segundo perfil para que muestre los existentes en "default-release".

**Comment by Marzal** [comment]
> Compruebo además que este bug es más notorio en una instalación limpia de Firefox 67, ya que a partir de ésta versión recientemente publicada, por defecto se crean dos perfiles (https://blog.nightly.mozilla.org/2019/01/14/moving-to-a-profile-per-install-architecture/). El primero "default-release" (perfil por defecto) y el segundo "default". Así, un usuario común que desconozca éste doble perfil y que instale sus certificados en Firefox con normalidad, comprobará que Autofirma le dice que "no hay certificados" ya que está buscando en "default". Es necesario eliminar ese segundo perfil para que muestre los existentes en "default-release".

Gracias por este comentario, estaba volviéndome loco (no habia manera de hacer que Autofirma reconociera los certificados)

Probado en ArchLinux con java-13-openjdk y java-8-openjdk/jre, y la versión de Java da igual, lo que lo soluciona es tener los certificados en el profile que Autofirma espera, que no es el que usa FF por defecto.

**Comment by jme52** [comment]
Buenas tardes,

Me he encontrado con este problema, he hecho varias pruebas, y parece que el Profile de Firefox que AutoFirma usa es el que aparece primero en el archivo `~/.mozilla/firefox/profiles.ini`, independientemente de que sea el predeterminado o no.  Parece que una simple edición del archivo de perfil es suficiente para 

Sistema: Debian con un mix de stable y testing, Firefox ESR 68.4.1, `/etc/alternatives/java` apuntando a `/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java`, y AutoFirma 1.6.5.  `~/.mozilla/firefox/profiles.ini` con 3 perfiles, que en el archivo aparecen ordenados por orden inverso de creación; en el más reciente (primero del archivo) no tengo ningún certificado, sí que tengo certificados en los otros dos (además son conjuntos de certificados diferentes, por lo que puedo ver qué almacén está cargando).
```
[Profile2]
Name=p
IsRelative=1
Path=awpnbypy.p

[Profile1]
Name=work
IsRelative=1
Path=2wwmhpph.work

[Profile0]
Name=default
IsRelative=1
Path=7lekpbsm.default
Default=1

[General]
StartWithLastProfile=0
Version=2
```

Inicio AutoFirma, y no encuentra ningún certificado en el almacén.  Edito el archivo `~/.mozilla/firefox/profiles.ini` reordenando los bloques para que el primer bloque sea el del perfil que me interesa (`[Profile0]`):

```
[Profile0]
Name=default
IsRelative=1
Path=7lekpbsm.default
Default=1

[Profile1]
Name=work
IsRelative=1
Path=2wwmhpph.work

[Profile2]
Name=p
IsRelative=1
Path=awpnbypy.p

[General]
StartWithLastProfile=0
Version=2
```
Reinicio AutoFirma, y correctamente detecta el almacén del `[Profile0]`.

¿Problema solucionado?  No exactamente.  Parece que cada vez que se abre Firefox con un perfil distinto al último usado el archivo `~/.mozilla/firefox/profiles.ini` se reescribe de forma que los bloques recuperan el orden inicial.  Se puede guardar en `~/.mozilla/firefox/profiles.ini.bak` un backup de la versión correcta de `~/.mozilla/firefox/profiles.ini` y restaurarla antes de utilizar AutoFirma (el reemplazo funciona incluso si Firefox está ya abierto).  Pero podría ser más fácil...

**Comment by Marzal** [comment]
Creo que en estos dos commits está arreglado el problema desde hace algunos meses, pero falta que salga una release para comprobarlo:

https://github.com/ctt-gob-es/clienteafirma/commit/fe24ff4c5c8ed36857e27f2f35c3ef8b9200ecc2

https://github.com/ctt-gob-es/clienteafirma/commit/456f4d56a7d949afa188c29f4f33324aeb408881

**Comment by Gamuci** [comment]
Efectivamente @Marzal. Con esos cambios debe funcionar correctamente la selección del perfil. En AutoFirma 1.7 (que esperamos que salga próximamente) incorporará los cambios.

**Comment by rmunozrodriguez** [comment]
> 
> 
> Efectivamente @Marzal. Con esos cambios debe funcionar correctamente la selección del perfil. En AutoFirma 1.7 (que esperamos que salga próximamente) incorporará los cambios.

Acabo de actualizar AutoFirma a la versión 1.7 y he comprobado que sigue sin mostrar los certificados correctos de cada perfil de Firefox. Ocurre exactamente lo mismo que en la versión anterior 1.6.5.

**Comment by Marzal** [comment]
Yo solo veo la 1.7 para Windows 
https://administracionelectronica.gob.es/ctt/clienteafirma/descargas

Y en este repo no hay tag o release aun con la 1.7 tampoco
https://github.com/ctt-gob-es/clienteafirma/releases

¿Están para Linux en algún sitio disponibles los binarios?

**Comment by jaragunde** [comment]
Este problema sigue sucediendo en la versión 1.7.1 para Linux (obtenida desde https://administracionelectronica.gob.es/ctt/clienteafirma/descargas). Solo después de borrar los perfiles secundarios del navegador, que uso para pruebas, autofirma logró sacar la lista de certificados. Había tres perfiles, por si supone alguna diferencia.
