### ISSUE TITLE
Autofirma me cambia la barra inclinada por el guión bajo al usar la función saveDataToFile()

### ISSUE THREAD

**Issue by domgomcom** [ctt-gob-es/clienteafirma#96]
Estoy usando la última versión de autofirma 1.6.5 (windows 64bits). No el miniapplet, sino la versión desktop.

Cuando uso la función de firma (MiniApplet.sign()) me dice que está firmado correctamente con mi certificado e incluso puedo ver el resultado en una textarea. El resultado es tan correcto que incluso puedo copiar la firma (copy/paste) y el resultado lo meto en un fichero de texto que se puede visulizar como PDF. Todo parece correcto.

Sin embargo, cuando uso la función MiniApplet.saveDataToFile() todo parece ir bien excepto que el resultado en el fichero es el código base64 (no binario, como dice el manual). Esto no me importa porque es así como lo necesito. Lo que es peor es que coge TODOS las  barras inclinadas o slash  ("/", la que está en la tecla 7) del código y me las sustituye por guión bajo ("_")... con lo que deja de funcionar. La barra inclinada forma parte del conjunto de caracteres en que se codifica un fichero en base64. 

¿A alguien le pasa? ¿Alguna pista sobre como solucionarlo?

**Comment by domgomcom** [comment]
Impresionante. Llamo al método MiniApplet.save() usando como primer parámetro una cadena de caracteres:
!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~

Y lo que se graba es esto:

!"#$%&'()*-,-._0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~

O sea, se carga la barra "/" (la sustituye por "_") y el signo más "+" (lo sustituye por "-")

**Comment by Gamuci** [comment]
Acabo de comprobar el guardado con AutoFirma y el método "MiniApplet.saveDataToFile()" y me ha funcionado correctamente. La cadena de entrada debe ser un Base64 y los datos se guardarán en binario. ¿Estas pasándole los datos en Base64? ¿Se replica el problema con la página de ejemplo que se distribuye junto al JavaScript de despliegue?

El método saveDataToFile está preparado tanto para aceptar una entrada Base64 corriente o Base64 URL SAFE (adaptado para no contener caracteres que puedan producir errores en una URL), en la que el caracter '+' se sustituye por '-' y '/' por '_'. Para hacer esto, se transforma el Base64 de entrada de un tipo a otro mediante la sustitución de estos caracteres y después se hace la decodificación. Tu problema se da porque no estás introduciendo un Base64 como entrada del método, por eso, a pesar de hacer la transformación de caracteres, finalmente no se puede decodificar la cadena. Por si hay dudas, el Base64 URL SAFE está recogido en la [RFC4648](https://tools.ietf.org/html/rfc4648#section-5).

**Comment by Gamuci** [comment]
Se cierra por falta de respuesta.
