### ISSUE TITLE
Errores de compilación

### ISSUE THREAD

**Issue by FJGL** [ctt-gob-es/clienteafirma#98]
En master en el Commit 24f53dbe1c9a1a11ddef777902743900ce5e7bd7 de clienteafirma se renombra la constante KEY_MODE_PASSWORD como KEY_MODE_STRING en es.gob.afirma.ciphers.AOCipherConstants pero no se actualizan las 4 referencias en es.gob.afirma.ui.principal.Cifrado de afirma-ui-standalone ni las 2 en es.gob.afirma.applet.CipherManager de afirma-ui-applet. 
Por otro lado en el pom.xml de afirma-ui-applet el groupId es.gob.jmulticard de la dependencia jmulticard-jse debería de ser es.gob.afirma.jmulticard

Saludos

**Comment by Gamuci** [comment]
Corregido.

Muchas gracias por el aviso.
