### ISSUE TITLE
Problemas con firmas XAdES

### ISSUE THREAD

**Issue by FJGL** [ctt-gob-es/clienteafirma#99]
En el commit 45774646cbc47da4cfff46e7ba409cfb32177a44 se ha introducido un problema de regresión al reintroducir el bug resuelto en el commit 9e6f4af365aeb3f167e6b6fef08e65c0c3537f10 que causaba que si no se indicaban las propiedades de la TSA fallaba la generación de las firmas XAdES

Sugerencia, en lugar de como se resolvía en 9e6f4af, parece más intutitivo chequear al principio del método los datos de configuración de la TSA para distinguir que no se hayan proporcionado los datos (firma sin TS)  de cuando  estos son incorrectos (Exception) en:

XAdESTspUtil.timestampXAdES(final byte[] xml, final Properties extraParams) throws AOException {
    if (extraParams == null || !extraParams.containsKey("tsaURL")) {
        return xml;
    }

Un saludo.

**Comment by Gamuci** [comment]
El problema queda una vez más resuelto en el commit 627810e554d8ebe8e2c40ffd1b1de0d1b68be2e3.

**Comment by areus-fundaciobit** [comment]
Una sugerencia. Si dentro de los mensajes de commit se añade una almohadilla seguida del número de issue, por ejemplo "#99", éste automáticamente aparece en el timeline de la issue.
